# yamllint disable-file
{{- if .Values.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ .Values.probe.name }}
  namespace: {{ .Values.probe.namespace }}
spec:
  interval: {{ .Values.probe.interval }}
  module: {{ .Values.probe.module }}
  prober:
    url: {{ .Values.probe.proberUrl }}
  targets:
    staticConfig:
      static:
{{ toYaml .Values.probe.targets | nindent 8 }}
{{- end }}
