# yamllint disable-file
{{- if .Values.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.rules.name }}
  namespace: {{ .Values.rules.namespace }}
spec:
  groups:
{{ toYaml .Values.rules.groups | nindent 4 }}
{{- end }}
