apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: app-secret
    namespace: blog
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:2Czp9pvH59xZ1g==,iv:hJ61mK/78OP6ulYH0XWNikSl4zU3rTQIZY+89B9Kv3w=,tag:a2qWyn0r1bi2hToQ2cJRRQ==,type:str]
          stringData:
            PORTFOLIO_ADMIN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:c9tQie8hgMvM4su56bqehusUc+Dr9+BUAgbPR18h9OFmHR2857T9XfIprMwyk8drgF9PAOonVapKLaIrxdwLAQ==,iv:juAvtUOxj3pZKWS0z+BhVF9q/7M9PwUhEkkCfcGOEm0=,tag:Q2qAOVRf4dqrYRIcXrvJ6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z1pJRkd4bVhPU0FIZmx4
            OEI3aEdrNnUxZWJOd3JIVXFnS1RLM29zczE4ClpqT2s3OFBia3lmeHpTNW1pY2xq
            Z1NxWWFkQUcxNzZHZHp3NTBXUGsyUWcKLS0tIGRIb3FkclJUTVpXQ00yVmN0cnIz
            SUxKbzBPVG96WXR5S3VxNy8rTWQrMnMKGdtE6IeI9cL7ynKMfw39AQ7eUmR0d9GW
            UaJC9/mMX2R4uNvYG63IPo66eBzwcpCWzjmryq+3ygPoC0xc8eGiMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBN05GbktV
            U2lXc3FPV05XcUUwR2Vic2pIUjRSQ2U1Ny9NTmRwMDJJK29QNwpQNUplM1ZwNnRt
            dHpuNm5XRTF1ZzBmVGJqUU9ZMms2eUxvN3M5cXpCWGRBCi0tLSA0MjMwWVJIcUU4
            TloxTUd6RS95NGxlVUxSNmJTcG1LQjFWQUwxUGVOSVM4Cqd4aIZDeBZ17KbP/wI4
            KuFMkOdIFQOGk0wA3Yzlfm+ji/48zJpLqx4g6RQUAY/oSFbu5WjqNHcL9F0c29bP
            CwY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WlFxRCttT1BNd0NUUU5h
            U1pIdU1yVkVTaGhHZGMwYnRJUUtFZ2VzV0FnClA5UlF3c1V6ZE1UdmM4cy9mVzlj
            d0xLcERrY1ZidW9ZTFZLbGgwK2xET1kKLS0tIGpaRmNhTE8wc01RaFdLRlZDeDJw
            ZHFzTExXMXduUk04UUJRUE95UGFZeDAK96TGEfAF7Y+P4PnBkEWO9ZgwIwzLYncw
            e+4ViaDu96YcgUYlyZjED+c+faQiUpY95QmsVqJfML5JnfN9cWh1ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-28T18:09:52Z"
    mac: ENC[AES256_GCM,data:ilL+YKIcVvd0wASCrlyI84RvwMSK9CY4wdMn8MvLDVTZSqs4UIVw90Utldok4s6JFcZDGf5SV9vFwhcg9I/jlz2ZHFJaWNjbPHY6+H8jYPEqv1dV620kBzeLgvkWyL0rWYYzv5jyVssSDPjF/BIteWBc+OJJEfVn0JahBFHovjE=,iv:vIGCez9JJoEUC03IPtyJlLn2A9RmeIZ6xwtzvY+BFoc=,tag:HWiQL6bf/Yqzw5tXfUMQPg==,type:str]
    version: 3.13.3
