apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secret
    namespace: blog
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:BSDGLd6tg4XcHX9+kfMaU022,iv:O59wm5PPRwHDBmRgph1BHGHjCd7a+XGVKSYt/1ZmVEM=,tag:i/4S5GSngGXvkLAytJ2WeQ==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:MRSv/WwCBOogLniHpRaKogVbh+4aKnQh2zCNDqtlEQ/1hfjKEuTejB3xp3axiRUHwQGwjdoFJ+LO7fjz04HUPu4hvEB2midW+rrPBO4JzBBDtsC0pfc9DmB8bzf6HDO4Mj6/r3fybQR9KJnUwf8cHWdEQRVa9yhVTlKbEy+KVZK3W3NGz/mGFLbfWhJqj0Epu56ScRXgZ/eBBrQucLZPGVbcN+IoimHc6oYqZZBnu+k/FxgnODsGNtXg7EiN8/YYuwStzgw8bP9R4A4i/Yuuh9wom4kvcXAL/ATXvMGg4a2k0qhwHHe5FvWB8cj0RUO8,iv:phg31L+OjsSXlIzJs83BCTfSDfjRFRy2o1LiusojOZ4=,tag:Iwh6absQjYjkGcobgVu7jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYmkzS01UaEFRVkQ0NmRG
            K2grZWpXRFVvZXp4UVdyRmhUd3c4TlFZYmdzCjZHNkwwTnJtMlVWQXFtYkxIcWRZ
            T0lkQzJrcU9iRUg5V2wrY2xhZHZSdDAKLS0tIFM2NmpjR3gzWitoWFFXN1FwQ3hJ
            NVdJMTZTMmtpUHc2TTJxTHRpbytrQ2sK7FfPEYGonN9Ar3mF5KQwkx+wmMKGmYEh
            n3PHPoYgFQsRlyO2PgRJ8vryTfdXBzsb+mRygPTCcnTY7jY+qoSv/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBL3luM0ND
            R0NNNFBuOGZUbUlzaG04MXZXMUpPYUtSYUMrbnd0ZFZCdGhaSQpvSmdxUGVTZVRV
            Vm9CNmd0ZTZGRVFkRTBZZkFXWEMvUWJMQnk0VllMM05JCi0tLSBYN3lpb0VrVi9Q
            NGtudGE2WlQ1M3JaQzZFak5HUDV5YUR0TDlkSnAwUkM0CovApbEaUPvuSSsVTc58
            JlBTGKjw0tPrJszP32MlwWgt1Q1NHOH0BXszhqAr1snhMfYR78cEY9ZQqJWvcIzG
            YFs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTXIzWFR1Wkswbm94RVVa
            eTFjK01NTmIveU1DNWRLOEIzZlFBbGFiYkY4ClBmTUQ2R0p2ZlpmaWI4cVQvY3lV
            R29aT3dTSlkyd1JLeVdabmhaVEhuZkEKLS0tIEtpejluekpQWW5YMkx2ekhyTzNz
            eHI3SEtyTE1kOE4xWVpHa2RJSW92TmMK15YpYvzdkdoM+LHrOkiUmGIi9cuhkIoK
            I7RN0/lC80zGyu5cStfEiNCkCP8y3oiwB4EC/2a+q20NEGYqdvNHTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-15T00:43:47Z"
    mac: ENC[AES256_GCM,data:y1Y9b9cMPjQ6cOJsHAvibpnQYhM7yMVGUquNs01Zvl8jiaPQkaSLMPEPhc3tmoUriXuaTI+isFssmw7lvaaBIGyTvikXvAWJdoQMuRQKbptWgsHGuoywqDjqi00oPD1D5u1qZaGqlpUTajvkSFFxvtBhapcuqKWYCQe0Y50at20=,iv:m7pFtI5KSVF++cfVrcoXsSMV6GPQ4SmJKN2J296hQR8=,tag:Oci41s2Uzh8xMX2YWT7qLg==,type:str]
    version: 3.13.3
