# yamllint disable-file
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
{{ toYaml (dict "secretName" .Values.certificate.secretName "dnsNames" .Values.certificate.dnsNames "duration" .Values.certificate.duration "renewBefore" .Values.certificate.renewBefore "privateKey" .Values.certificate.privateKey "issuerRef" .Values.certificate.issuerRef) | nindent 2 }}
# yamllint disable-file
