# yamllint disable-file
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.internalCa.bootstrapIssuerName }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.internalCa.issuerName }}
  namespace: {{ .Values.internalCa.namespace }}
spec:
  isCA: true
{{ toYaml (dict "commonName" .Values.internalCa.commonName "secretName" .Values.internalCa.secretName "duration" .Values.internalCa.duration "renewBefore" .Values.internalCa.renewBefore "privateKey" .Values.internalCa.privateKey) | nindent 2 }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.internalCa.bootstrapIssuerName }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.internalCa.issuerName }}
spec:
  ca:
    secretName: {{ .Values.internalCa.secretName }}
# yamllint disable-file
