{{- $auth := .Values.authMiddleware }}
{{- range $namespace := $auth.alwaysNamespaces }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $auth.name }}
  namespace: {{ $namespace }}
spec:
  forwardAuth:
    address: {{ $auth.address }}
    trustForwardHeader: {{ $auth.trustForwardHeader }}
    authResponseHeaders:
{{ toYaml $auth.authResponseHeaders | nindent 6 }}
{{- end }}
{{- if .Values.monitoring.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $auth.name }}
  namespace: {{ $auth.monitoringNamespace }}
spec:
  forwardAuth:
    address: {{ $auth.address }}
    trustForwardHeader: {{ $auth.trustForwardHeader }}
    authResponseHeaders:
{{ toYaml $auth.authResponseHeaders | nindent 6 }}
{{- end }}
