k3s_api_allowed_cidrs:
    - ENC[AES256_GCM,data:3Xfe+isIqUlBaCdbQA==,iv:eOrIg+dfQsOaY5/PUEaGHYIiXHRqoUXK3t8K5bwar6I=,tag:Mbppt1FIKD4Bw3XKe4jacA==,type:str]
    - ENC[AES256_GCM,data:GGzzOFiEX5lCGwIIAg==,iv:dZqSNgik9MfxacGmEfhgSInlX8oL8vfPLjBMzMxvl/M=,tag:8WoBcGPQ6LyrJz8RH8ZZwQ==,type:str]
    - ENC[AES256_GCM,data:CZJfdQhMzVFG94U=,iv:ONVDG6XS8hJ0C76H+e5g4sQJ4lsnTGJ7ZCIpyrqKu3s=,tag:XLC6uN+B4Q0fHbhzZe/VaA==,type:str]
argocd_github_webhook_secret: ENC[AES256_GCM,data:pqTQ2jJB3Vwjf+xeOln+vWzT36/G37zBcp6rCcBaAduXuqzDOHXP4qd+H1Rpn5zTCAiKrtDHCy2jSbvyalVN8Q==,iv:/TiF4GNsNmPTO5r8K+rfAjeCL/Tw/uCdNJMbOIVc4V0=,tag:sHXFc2Evk42SKMCEV624JQ==,type:str]
k3s_join_token: ENC[AES256_GCM,data:VoCkdAUMJkSsX3UVpZ0yNLp2Z9gQebsZHr2B9TkBHksCsmu4jFELPXcWnI43XYIowj34BUf9TVp6Oc+XKJY9KKErGBXVUoeriUfPrkO27LzbQJv3TplEq9AFcTp0fNmY+0nRiBZbBeLaEP1J,iv:/DDHPXOtOohN4sf9wsfy7K17gvFo/nfc3erpuyIFVSU=,tag:qPMAIx+0STKkc6J+LpF9Pw==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:n4w3WyO6qr39lFEqmKweiSp2Egm8CUHgesIU4jw2blo4//Gaq4Z2/0iwGfh33M4hG1841+QQcJPkTWP583k=,iv:h8DXezU7vDQlI1AfRXXzLHxqUxjMiMipK8MfZKKXp2Y=,tag:xFnWNVvuV/xy3tx5gvSbZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBaEhBUjB2
            RWU0NFd1djFlMXlCWUgvb3RZVUFNNFBweXh4cm0zU2RtQzZZRAozNHJBbkw0UGtO
            WlVVNEhFdzZhdVVGdHV3MXRJRlU2OFNjN0FPcWVyQ2pBCi0tLSBGcXNDdHJLZEd0
            NXJ6anR1YjdDWlZ0YjJTNFZLTlE0cGtlOFViNHYxb0I4ChKDft1kojoBSCAJaF9y
            /L27OGqaYE0bAODMROmIVaOgpApgVwNoneAH7faF/BuNcyigY9PBYYLkWSerkZ/U
            3F0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR0dWMm4ydS9aVUdCamRC
            S3YrU2d2WlczTkNhcFZBNEliVTltd0pYRXh3ClpMdUcvWmhoK2hzVjhsNmRKeVNh
            ZmNDQ1FTRFlwVnJpM3MzL0l2YnhQbXcKLS0tIG8yZDlTVnNxd3I5K2VwanRqS1o2
            K3IxOFFGNWtjazZ3VWplZGc4MUF3MHcKQMScRCa1XJnQKs5LTH3n4z5J0nnwGqQ9
            lWfWM6m7C8NfZ3HmnNSLxvzxWQWgBPJyN5dV+xYyr/s4hORxhs63SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    lastmodified: "2026-09-16T01:01:51Z"
    mac: ENC[AES256_GCM,data:msfl9hezTLmV2wXBH6Q6BztWant3Th92KqJIVVnDqEsO1D16X5UT3B/L5398PEUTwm7GDYjIKwXLaPIIeZ0MlZs82SCt77bFSHzHeOOZzMkXXWbEluqiW3sJok4VWJZLqdHb/xWt7q7wvIn2rDeUBDdLtQ/lZKudMbfejGZ0/vA=,iv:zbaIZAWQ3fvqYCYPgjSUVJDlnYhUSkB91emoIieocqo=,tag:MG6I5z1GTSKxVq+WXuUBaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
