k3s_api_allowed_cidrs:
    - ENC[AES256_GCM,data:P9qZ1ogmI7K4piTIxA==,iv:SnuWl+hUZQpuLUDTNY9MII6FtMszG+yhmbuEaFoa7mQ=,tag:TvP89BeVwJqUiLGv80kfaA==,type:str]
    - ENC[AES256_GCM,data:9GRKIEf9u8heGzySZQ==,iv:hnGN6/iEvizYpXZWQm40a0q9ReuayHaidbbuPrMURhA=,tag:EUYoVcCL0mC4RuMusILHtA==,type:str]
    - ENC[AES256_GCM,data:D5Rfrx7gvWnlta8=,iv:ByBsSmk4AEfCiWudApLf96MA8zG80jUBxDB7riDGhjU=,tag:0xexvfec4Xct06kdQPT8bA==,type:str]
argocd_github_webhook_secret: ENC[AES256_GCM,data:cUQxgaym/hM7x93Rb0/Kqufb9NKidpF+YplW2Q+MMa0HeAH11nD2nJg7pF7B/cI/XkwTT9jubCLqAIIYDuniSg==,iv:DHTZ8m2pVJNarKoLXk9euck/rNbQTXtaGmGIyCQXofA=,tag:0rCSaTvSfteu5o5GyQ/vaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBbGhzRU1s
            ZkFHRVNhb3RucnlqSkZqWWFpTjB3WWpXT2Q0QjBFUUJ3WWNsOApmMTZjYXdBUERv
            a09nSi9EdGNqaFVRSXdVVm5KVGZRTVZoYWQ2dGVra1hrCi0tLSBtSnZFd2haUWp5
            aTIzdWFWb1gyYmJ1U01hUTMvaHlZaHFLOWhNZHkvc3JzCkd0MmVu87LAxVezj6g6
            Er1f443i0fKYHdx8CEhOjjqa79JYK9vIVD1JjLHU8X8X+qDaSLZD/uwPKU9r4dPm
            GVQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY0xhbGVsYklxU3JyQzVR
            NU5kMlFaTHZUVnNQdzFRWGVYaER2Nm5weVhzCk5CVTBUN2dxU3J4MDdibXd0R3F1
            WWE4UEhBaGtoMUpkNU5qTy9KYlUrTFEKLS0tIFVOU3ZoZUp1bTdCaDhna1hBQUh2
            cFJIclhvMmJEM2oxNlFSTVVuQkRHc1UKnHntE9vlJW41yjR8fgzWkJa0bkN80qqK
            9YdF5+e6/AmJy6Ma2RXNDSYB/euPBM0Rq8uOZjXOdhy10qwznMtZRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    lastmodified: "2026-09-15T15:28:23Z"
    mac: ENC[AES256_GCM,data:n+cpXWBO48iPAliXSx+BEdyeMLfZ6ZjbWBR3s4O+HThTZkhXvAD3Q3NXN1exuhW67znrjQLIZMHg+7wt8kcdYFankUOrseO4K/pkPZ3wjfRUsDCkWYgMpooInCK1IY/F9vrPJZ/Eog4fzRnM0P3tAR2shNL8W9nmIj2ygHuwZYQ=,iv:jKHc6E4yDP93NuenbLwo5CKCJwfHpmaSkRLfgHicrw8=,tag:IS8j/d+1Fa9uikfnGzgkSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
