argocd_github_webhook_secret: ENC[AES256_GCM,data:pqTQ2jJB3Vwjf+xeOln+vWzT36/G37zBcp6rCcBaAduXuqzDOHXP4qd+H1Rpn5zTCAiKrtDHCy2jSbvyalVN8Q==,iv:/TiF4GNsNmPTO5r8K+rfAjeCL/Tw/uCdNJMbOIVc4V0=,tag:sHXFc2Evk42SKMCEV624JQ==,type:str]
k3s_join_token: ENC[AES256_GCM,data:VoCkdAUMJkSsX3UVpZ0yNLp2Z9gQebsZHr2B9TkBHksCsmu4jFELPXcWnI43XYIowj34BUf9TVp6Oc+XKJY9KKErGBXVUoeriUfPrkO27LzbQJv3TplEq9AFcTp0fNmY+0nRiBZbBeLaEP1J,iv:/DDHPXOtOohN4sf9wsfy7K17gvFo/nfc3erpuyIFVSU=,tag:qPMAIx+0STKkc6J+LpF9Pw==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:n4w3WyO6qr39lFEqmKweiSp2Egm8CUHgesIU4jw2blo4//Gaq4Z2/0iwGfh33M4hG1841+QQcJPkTWP583k=,iv:h8DXezU7vDQlI1AfRXXzLHxqUxjMiMipK8MfZKKXp2Y=,tag:xFnWNVvuV/xy3tx5gvSbZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVnRJR1dSSklBeXZHRUlv
            MFBqSFNubW5qMGNGcWw4ajE5Tmd0YlV6SlVrCnZpVjFaZzE2V081SlpDQUVLZGl5
            RURJd2E5ZGhoK0wwOVFLeE1MRWpJS2sKLS0tIGtFb0dvc3JCUEd5N3ArNjdsWGdq
            NnZaaHc1MXJyUnRJenpiZmsyYzBseEkKJDOmHdMk6vXhBzr9jvPybtcTto02kL1P
            Zcgt7vEeEXxpGhK8qpwSWvY8o2KnqMUsW/eAzpYOHzBrV4fR2V9NUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBNDRhM1h2
            MnFaUm9BNVZXSjN5OW1zSjdSeUpQN1hhMGhxVCs5QjZWTWJUZAorb1dQMXF4ZTVH
            OGlYTUpJNG1DeEc5dFVWam5lM1ZTVHpOZmNQY2pRNkZvCi0tLSA3Q1lGeG56NmNk
            VHp3UGRCcElhd2w5VndLbm8vYmdZRG1uT1lGSjlDVHFzCsPKspCp1Tbxt9P7qqJF
            10zqtukCwW6MKEe5b0ZqYbqD31TAlQInvzyOl5cn/WGSJo6z6nWzqszpHh1FvXUd
            Fvc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS0V3RklRUU11L1RkZHgw
            SXVJVnBJbzRLdzVOU09mR013OFFDbk5VUGdNCmJ6RkU1MTBEV2plYURNa25TdW1Z
            UldvQWpLemtkdGMvSGp6YmE2c0puKzgKLS0tIGNkZ0w2R24wRWxWSFNNNmtDUEgy
            SzBHL2hYQnRSZjJQT3FGVnZtUUNTek0KM+hNUALAuXLedcc1clj7DFkqecpzRsv4
            X8CHUM+ziHg8tUo6argtBtc+FAfRqIYp2BfH/tq3AUQe8XcHegSxig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    lastmodified: "2026-09-17T17:08:42Z"
    mac: ENC[AES256_GCM,data:o/lW6jmY8uXhn+vzxJCL3p1fEO8ShOScKlhdI+M+spTdFvYxOUnGfDggPQD6mr3iCgy+dwMkYvhPZcB/iYmgtZ88XmXX1DZBOq80D/PF80SlTpfqWGooXPwm0PGU8j05x2EycByg/OVmc4AN7FbcdoSayYg+CYOzV1vT1BNFC7M=,iv:3vvYSRkz/YQ49VoQNmNtYxxpSCSk+LJwNVsB04lNT9I=,tag:ZZT27YFIX73Z7hAo6jt0Pg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
