apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://github.com/guesant/hl-infrastructure.git
      targetRevision: main
      path: argocd/applications
      directory:
        recurse: true
    - repoURL: https://github.com/guesant/hl-infrastructure.git
      targetRevision: main
      path: argocd/root
      directory:
        include: project-*.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
