apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: satellites
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  description: Application repositories that only manage their own namespaced resources
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
