apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: satellites
  source:
    repoURL: https://github.com/guesant/hl-infrastructure.git
    targetRevision: main
    path: argocd/apps/satellites/blog/blog
    helm:
      releaseName: blog
      parameters:
        - name: application.deployment.image.tag
          value: sha-c00a7684852c182bbc38fb7c1be82b14e0c5302f
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
