apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: blog
  namespace: argocd
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: blog
      images:
        - alias: blog
          imageName: ghcr.io/guesant/blog:main
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            helm:
              name: application.deployment.image.repository
              tag: application.deployment.image.tag
