keys:
  - &node age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
  - &operator REPLACE_WITH_OPERATOR_SE_PUBLIC_KEY
  - &dr REPLACE_WITH_DR_PUBLIC_KEY
creation_rules:
  - path_regex: .*-sopssecret\.yaml$
    encrypted_suffix: Templates
    key_groups:
      - age:
          - *node
          - *operator
          - *dr
