apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: oauth2-proxy
    namespace: oauth2-proxy
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:yzSC5nZDtGdqEJDo,iv:kpu4MAb2kJz87Z6RHFqBMrg0Nn6XtkD50JYz0omi37w=,tag:iNl41qVhBXEJD/IzLJzydg==,type:str]
          stringData:
            client-secret: ENC[AES256_GCM,data:jGq+MaGzkfqlxGkJcUozSZDTg/ogWxXk8M12nIJrZcltZct1zHiZW5zKd6+W/Yz4zxUyUXzg2+kx2UUVjQJE0Q==,iv:0GReK4cwAPzo4Cw9L8sl/SL1vendNpLvuyMOBySFSZ0=,tag:aOuFAN5dZA+2Ip3FfPxlSg==,type:str]
            cookie-secret: ENC[AES256_GCM,data:5Os6+0laev70rARQhzN7VXpZ0/vq2/0UXBFe1J3pvDUcPKoAAyB+lrZXpw==,iv:+f/CqWaDVYxxw9ujcL9qlgyOIY4ifTMzGPKB/d18zAU=,tag:ph7zlhzXAeZTGfD0ociIyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBckV3V2pT
            MmpkM3BWTk1tTTB5S2tDUURlVDd5N2U2TTBIS0ZQSDZlR1VnUwo2b0o2M0pyUmZ0
            MFV0WTlOa2I3RURESk1NR0svUGd2RjJUTzk0WFkxdkNZCi0tLSBkWTVUVHpDcmlB
            MjhpdnpZRmhuUFBQdzUrbytReTFZSmtFTVFkYWQ3UXhrCs85eGVhc0sBFRO38h/Q
            IqsOcbbpi4cUX9zy+pE8IJRSTOS5gm20TbjOsg+KZ2n0kVCB9EHQZhujhULKRKcF
            3hQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bDdlOFFSQ1Y0QUJPQmNn
            QzVZZjczL3c5Z09LMEpHVTU2WUJwY1VoOGdJCnVyS1g0QUtYTGFBZ0JLLzFRY1pH
            dGFmMEUwdkQwMnBHUnRWQnpJSWlKbHcKLS0tIEwreXNCL2R1V2p3V0Npa0lBSDJo
            azZLeDFvd045KzNnMlFCcEE5bldBaUEKQN6sP8JYixWpmFJQJjvSunRMe//cAJtN
            WpNXEixyxVyotBqDf+ZNOTCRIfkD1tTk3V5CbmjyUGaOLiTsFErHiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T11:53:30Z"
    mac: ENC[AES256_GCM,data:Q8x4T6xY5MI96oPuYhnvfBxkgt0aXbL7zO4+Bx2LuXU5ZpNjiXt1k35OIYHUyEviySYPELJcmI2MKY5kK/Lo1Zy0J/iudJSVH1hGQ+hCOJDRfzV9HSRztFQPVqsO5DdoYxQSJ6mHnjD0kVVxQe/skRLPc1O4qKf/BzJaKc61dyQ=,iv:KBDJabSZiylV22MvkfaB67YpXgO9Sgr2h9WtQ7VBBmA=,tag:RR6NNR3l+sW/Fhs9dof6tg==,type:str]
    version: 3.13.3
