apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: blog-delivery
  namespace: blog-delivery
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  promotionPolicies:
    - stage: prod
      autoPromotionEnabled: true
