apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: blog-delivery
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: blog
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: blog
                namespace: argocd
                sources:
                  - repoURL: https://github.com/guesant/hl-infrastructure.git
                    helm:
                      images:
                        - key: application.deployment.image.tag
                          value: {{ .Values.imageTagValue | quote }}
