apiVersion: v1
kind: ResourceQuota
metadata:
  name: blog-namespace-quota
  namespace: blog
spec:
  hard:
    requests.cpu: 550m
    requests.memory: 1100Mi
    limits.cpu: 3400m
    limits.memory: 2200Mi
