apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: app-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:xsHjYzCNRsOveQ==,iv:cJYD05yhX7ZT8XSyA88gFtrI6VaD9EYQAXZ9VdLa1uI=,tag:dI3EbNGgdPvH+y4CVbwo/g==,type:str]
          stringData:
            PORTFOLIO_ADMIN_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:qoJx3EDcI/TjnjtsM0iSMxM/nIe0oHFV1+KrXItItnJ0BTqNMkTnJFQLWoG0GCBBZAn/nfozrqHgAHhz/B/8kHM+MG7TmwJj,iv:vcNUCVJFH/lj7+7IEJ3QwaYbLmOVXsjlV6h1ZbfnjBM=,tag:dPKTQIIQwdEqOUPD9/ET0Q==,type:str]
            PORTFOLIO_ADMIN_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:MUIyr579NrRil5CcHM6adUAtIWXo6WEFjezwXPlgIbUmdr0=,iv:MF/fBRkjlqfZM7CAa+XwsuN5BdcOfdv4/ZUTtcgpSXQ=,tag:HvcsdPOx+5MYyadWM8MOZg==,type:str]
            PORTFOLIO_ADMIN_GOOGLE_EMAIL: ENC[AES256_GCM,data:OUWV3vsyogF+YPiVDfiYhgF3yF+Aqo3VDZtC,iv:Iu8ibFtosp37X2yJ5KBuU77jmnBkveYDRQtcdyxAcUY=,tag:hT51WrHJwXrxF5i2QCb7dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBb05HUWo2
            UURkUmxMZFdGUUgxWHMxTFJ6T3BkQ0NtTmNpT24rL042WFc2ZgpZek1qR3RUbTlS
            UEpMenpjb1NkT21GaE9lQWVFdi9OSEpJdGxhNXpmd3JrCi0tLSBFbVRIZUFEZStv
            UUZJcEZyVm14OE5RVk5WTm5vOXdyV2RHMFlkQjlLbCtrCpCE4eIAkbzsuqk4J048
            2UE6sdTHo3Skl8Rpsa71AUDuCebBI6EB41u6NnsQrhIrDkzgqNSo8mlpEdoR/B7/
            n/k=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU2JTUHpqVGt6WjMwcWZD
            cjNKai9qUXVxSnVIWWVDc09UaVZ0cFlCMVVFCmtERmxJTkhsNi8zQjlRTDA5OUps
            aWUxbFFyY2w2SkRyWTdNd2NTUTBPK0UKLS0tIC9QUkh3Z0pLMlJ2b2JKdm1ZOGRa
            cTVwcG1tYUh6d3paMk1pSTM5aGg4VzQKDVfCHt6c6q8viOYiC0PluhBy/te++qI/
            9FVgdYyK5S8AqNG0r0SFQs8aORX7omRHjhX+uHy0yW15gTdHYiP00Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-14T23:46:58Z"
    mac: ENC[AES256_GCM,data:k28JD4q2BpFUE2XiBL3pGvEjfE2EvGmGHqAE3A8V82nM/nBKolNkc3l5lxlYgOXwa4jd9OX6OBsCJ4oUMswBihLAOCUg0BBw+xVMdH8fG3LJ6CfQwLVXohLXxTzdObN/v37ZvzUv5l4EK+dBkhWOlPF/XHaV/e7Le7HgsCuMKgE=,iv:R4XncnWt6DsgqGIN9MICFCmVseyZQStCRKFm0IA1J6M=,tag:FoQJExbleANUp0Gba7wL8A==,type:str]
    version: 3.13.3
