apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: app-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:gvXxH2lFBqktzQ==,iv:keVqs77equxACIseVcsX389bfUG6vRst1FK1rLXtSTI=,tag:gXPyAMBLmCHbOHiVB2/MGQ==,type:str]
          stringData:
            PORTFOLIO_ADMIN_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:czWXM3SbRRcOwrUrdB/YfbyjHlbg1u0=,iv:RSsuH0GAK5C9Ny773Todp58J/nLlKtl0BbYys8tLCqE=,tag:AXvWlq6ZRcaYp6ukuoiSAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBa29RR3hG
            bmxTMkNkK053ckVQZWVGTENOc0xRME50aFN5YXVucERUdm5lVApQeGxwSktYWFgx
            aFdReWRpQ0lKdU5QZ204dzZHZkZ4N3d5S2cyemcrdDQ4Ci0tLSBNNm40WU1zVVNs
            TzVzaWRqTXQraGZTMklxSVBjVUZ3RDRnV3ppQWRvZW9zCta2tK4aXVcYxMlItFCO
            BakGbIbDEU6oKZ8FmQ0r3BxGSE55mglKXyQAUS3vnef4O+uH4cdW9JYwyNmIGvtI
            Rno=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSlJZYTdnd29nTjJjSXli
            TEVHQmdiZzdLdnpWWWMvbnlrZjBZMmUyYVNjClpORDNrUUV5bTMvdGhBbUFRbE1u
            eFhlVTJVbE96TjlMenBNTjBVRXdONVUKLS0tIDc2N0Y1bDZ2ZWJXU041bGNBSGt3
            djl0c3R2WTNMRkR3cEhhT3YvME8zMzQKPa0ah0zlEtVoS1qQR2xiwMg8+7bBi3FR
            m3zY/gDsv6n8o2emnECOpfApxCnkr0K8uwcTZEs4ynBnf1T5F6XP7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-14T17:42:59Z"
    mac: ENC[AES256_GCM,data:hN6n/AxzaMVoB3csNVIlXEn9S4hnX8kphS11R6/dBfGBpIspSLMAMDblEQZFdSk5xNZ8i8RvaeE7PQKjkI+t+eyVpZHCct+si6OHzdBO9C+Ca04ZgdoFg6JlF3lrRqUK6nr/ASX9NIzgJsmhIY6zloht9Ug+iKIXfEgGVNt47Sg=,iv:+8o9GqwkWCFZoJnX0JMcy93WW2bCLRgrtRkqzJ3EVxg=,tag:BE2SLEvXIc2SpYSim8RWGQ==,type:str]
    version: 3.13.3
