apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: app-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:b2joLWU/LeEpfw==,iv:eg1q7qVofNZmt/IZISjZDaUNePafjxdJE7Kg8xrUZV0=,tag:oaInu97QkZ9bXyO+GLUgcA==,type:str]
          stringData:
            PORTFOLIO_ADMIN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:iUo0Id1kHsEc4nVSGdP6M47WM0B8jmq//lv6L0CNfX19F9/uWBzdN4m1Juo2PqplY5Accl5wYt7VtpLkryq/NQ==,iv:mdRrgtl0aH4BZfTpvhy7xzsBuHU5G8E55rf05gAuoiw=,tag:/vD0pBEvZUpWa3z1CV1Qnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBaC8rQ0pr
            L0JTN2J3YVlLMHZ6aEtwOUhZYmk5VlB1Q2hWSGZRblcycVZIUQphU3pzY3JmOWlD
            RHp2WVgwSVVIV3NnK0JuNnYzRElrcGhZdldNTytySXc4Ci0tLSBSanovcm5WS01Z
            Q1pSRnFoR0VvOFZlcHFrYlUydWoyQjJWcE1kNEdyOEJRCveN0RJB0u5j3ihN18Q4
            N7sW23w3J6VzlRYpPARYDSXONk7oKL5FZhl6PFDuDpR3rjUBzjuQ4K249I+VL9uN
            nKw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeHUwY2N6Z2FPc0Vzcm8x
            S2JUNjFlUzhhSUJwVkNXN0pNNHF2eWFyREZjCm4rZm5CWjBUdXBFS0N2TGtYajZN
            dXJEUlNDejFjU3RvRDgrTWxqTkE2Qm8KLS0tIDRRS1pnbkdqbGhXYm42dGxvYWM0
            djI4MzlQN3E3d2d4NVV2VVdoYTlxeTgKQutIh39u07A/u1VT/naxUyd9wjJ5frBs
            SGvWRPIG1zfSqmM3CVzAF2gVGpkzDkn8XbRlS/Ir51Ep/A1GAJVnIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T15:16:50Z"
    mac: ENC[AES256_GCM,data:ZU7Fo0RoTp8+qgU0C6FqmU950oap1SJlNGmyMLF6QEldwLD8cZklvCWxO1Svl/ucsA1yUNi0hu/0kKCr8sbDpYwBOQGXUOwQ8rEKbUpQKCI37V16Z6B7BBIyv1WjEckNnEyZIsERs5XeIa1o8Dj7iQmlqnOZiAxicETnUjKBSfE=,iv:I+ap/gE/R2qEWdbIHgsdjCTBUht8hEraUR2l1p1Gxe4=,tag:XdZ8496KAkrw7yPZfP11CQ==,type:str]
    version: 3.13.3
