apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: app-secret
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:b2joLWU/LeEpfw==,iv:eg1q7qVofNZmt/IZISjZDaUNePafjxdJE7Kg8xrUZV0=,tag:oaInu97QkZ9bXyO+GLUgcA==,type:str]
          stringData:
            PORTFOLIO_ADMIN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:iUo0Id1kHsEc4nVSGdP6M47WM0B8jmq//lv6L0CNfX19F9/uWBzdN4m1Juo2PqplY5Accl5wYt7VtpLkryq/NQ==,iv:mdRrgtl0aH4BZfTpvhy7xzsBuHU5G8E55rf05gAuoiw=,tag:/vD0pBEvZUpWa3z1CV1Qnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOUhkKzN3eVh4UmkwZWxU
            dWdUSURlNFBnUml0UDhIOS9xTlBsbDFwL2wwCmNqRUlFNGUrY3hPcnhMNTd0NUlV
            cUFyNFpVYVhEVXEzbmtKalQ4d0VsVGcKLS0tIExxYjAwQWtxTm11QWJCYTA5bGlx
            Q1lVby9oMXRuTHdxZG1KRTBWUSsrbTAKBRVjX8CuP55hvDOElaSuP+d+IA/seTmd
            d+MUI0SGqu05Jl6TgrBbJv0/HqDuOIpfT3mNf0pbFhWRhkpCvUcANw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBajJUOXN5
            c0JBQklRWFE0TTBKTjhDK28zS0hzRHpKV2dxWTRMd3oxUjJRaQpmYjVmWTRXY0dv
            WTlsdjdnbTNnOFVTSzNaKytNMFNwQ0JjSy9LQ01KTFQwCi0tLSBCMnNPRnAzR0Nz
            ampqMXBWdVRzVWNHdDhVTjlMV3pWdGN5bmh3V1lzVzhNClDHBUJf0fN380q1zSlw
            Neaugl5JWYz6iUAPYfPBQYRUE1knRFXi7yyZV+KiwsS9Z2C5eP4NjuhK3lJmILRa
            h50=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKems2cVE1T1ViUndvL3NS
            aWFTOFdHNS8xYnMxQkRyVEJEaEV2T2g4UlVrCnJaTzFBWkV0aEZnTWZTbkdtUUJa
            Wit5SGhJNkFCWHpXaWFLRlM2Zzg4dUUKLS0tIGRJVkZwRmxERlhxbnBZUDNrSEJE
            OFVteVRkQXU2WmpuYXh0OVlRMmtndVEKURnCAy9Mr4mSRyW+i9Z6HMMjV56GUSQu
            UTcMw1qfxDUboDWAPlDJO0bXirGLIvY9UNXxGtK/VnWYUYsTq8FNBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T15:16:50Z"
    mac: ENC[AES256_GCM,data:ZU7Fo0RoTp8+qgU0C6FqmU950oap1SJlNGmyMLF6QEldwLD8cZklvCWxO1Svl/ucsA1yUNi0hu/0kKCr8sbDpYwBOQGXUOwQ8rEKbUpQKCI37V16Z6B7BBIyv1WjEckNnEyZIsERs5XeIa1o8Dj7iQmlqnOZiAxicETnUjKBSfE=,iv:I+ap/gE/R2qEWdbIHgsdjCTBUht8hEraUR2l1p1Gxe4=,tag:XdZ8496KAkrw7yPZfP11CQ==,type:str]
    version: 3.13.3
