apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: laravel-secret
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:p6s2RvOrgYXhvrZtO5Q=,iv:7Cj8C/Ecv4JS2R3XLbHyrNzZF9hrGB+WMWLoJRG8Z9g=,tag:79tPkZkstSiMzutBnZ45vg==,type:str]
          stringData:
            APP_KEY: ENC[AES256_GCM,data:9ZivEp6PoRo0Q7OvT+HuxZfVUphehbFcSjD3MzC17fnvfWt3XPLPhVo4+wWPJbwX1PTs,iv:713dU9P498mC9ngptOfWgTVwUKFDIQu+u1z8Il1CCOE=,tag:ek4e7GpXmNOuKD3t4mGhag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYUpkMXlnLzExeTRmN1J2
            d0RoWXh6V3REZVo1NXliWVFWekNLV2I5NEZFCmQxYnRKNG04ZTAvdE13U2UzdVgv
            RXJRWmIxdGsvbVRGTkNiRjJTZHp3a0kKLS0tIFhkcmZuZ213Vm5EcFB4eDVtSUpw
            RUtiMGIxSkpHTnB0UFRNdXZDVU1lblkKj+SD2Rb/KQR3hMjTpQuBxT+kcheDBMZl
            1PBhmzXjyTNfIYexKHic7sraAtR8shUhaIi6+XulBiYJVXwD5EyFjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBNkFvNGsz
            RDB1cjZWblo3REFVN2ZSc3o3T202VUZWSW52RG1BZE1qR3JMWQo1RE5qK1BKakdj
            Z3QvTlBmazltOE00UXRMakticzRiSGhNWGxOZTNuMDlZCi0tLSBLL09Sa1ZOZWhn
            Rk1IcGVIZm9pVHdsTk94ODEzeHltdVpnUzdPRmVnVjlBCqUhKHgm04xeAxnvEMK1
            7M8hh4BsYqCPX+BVOkEwNvh86XhkD0XW+j+n0i9ln0tozWYA01aWwTfxJpnCrqhG
            Log=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN083bjZrSUpKYm1Ma1BV
            QlFWem1DOThNNmNjYmltc3F3dFdFcnZOZzJRCkMwN0hTQ2pEQTBJdENVNnZvaXZV
            am5DMFlwTWpaVmJrZ1N5ek9FRGZPYkUKLS0tIFNtNGZGSzVwZFdRNjZFQS9CRU5F
            R2xXQkNtN3NNL2tQVGdRRjl4VW0xaTgKIJ2ZT/p/KTKIKJMYFYw8hX0wKsMZxhrM
            HQ+VHAC7HF5szgytakLpR2401aZcRI3GmttWjDyghHpncu6KWq7jyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-18T23:53:12Z"
    mac: ENC[AES256_GCM,data:ldB9MKpAEanka5gDsmUsfLC9c2fVMOftA3yHfIW/AU/ap6TVlgTXdo8cMRQqxEyR3/nBuXUKtwtQQwb3MxJVb0ZGkbA4WssOJQ53vAavey6lXm6Q/8v0bJ/LB/e/+pyyJU2/QeKxGc+4ikaMmLBTld+ZETJekMWquaCRISLlSrE=,iv:N05oiPJUgaDR3JlgGk5p3VAxaj7fUjGSq0AEj3deZ5w=,tag:vXoJYxpuFJLONTWpcxxBXw==,type:str]
    version: 3.13.3
