{{- if .Values.laravel.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: laravel
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
