{{- if .Values.laravel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.laravel.names.service }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.laravel.names.application }}
    app.kubernetes.io/component: {{ .Values.laravel.components.serving }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.laravel.serviceType }}
  selector:
    app.kubernetes.io/name: {{ .Values.laravel.names.application }}
    app.kubernetes.io/component: {{ .Values.laravel.components.serving }}
    application.stakater.com/workload-class: {{ .Values.laravel.workloadClasses.serving }}
  ports:
    - name: {{ .Values.laravel.servicePortName }}
      port: {{ .Values.laravel.service.port }}
      protocol: {{ .Values.laravel.serviceProtocol }}
      targetPort: {{ .Values.laravel.service.targetPort }}
{{- end }}
