{{- if .Values.laravel.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.laravel.names.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.laravel.names.application }}
    app.kubernetes.io/component: {{ .Values.laravel.components.serving }}
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.laravel.serviceAccount.automountServiceAccountToken }}
{{- end }}
