apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: og-secret
    annotations:
        argocd.argoproj.io/sync-wave: "0"
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Qc9mLEtiGE+s,iv:MQo6NSiOiuQrkhxxPezlx/fwwcs2ZHQPWPoUbhjOg8I=,tag:FlPFWtbrx1FYUcn/HSI2iA==,type:str]
          type: ENC[AES256_GCM,data:ocNaiuhR,iv:SYveZQiHjMWQuxUJVYB36raIIUFGIx+vzy6kXkbNoXg=,tag:6UN+7Jaf+EOISDfFzaQfMw==,type:str]
          stringData:
            OG_IMAGE_SECRET: ENC[AES256_GCM,data:xx/L9SIdc01ZfI/uQOqzML7SvfMq0KHLNL2HsGVWC3M+JtStDfXN7npl9jRbA1VOV5h35O+N2MD6jDDddxIEayYKlcXswgH5rYGX3w1FckOQjy9NJ0qtYAjE3/HmkDd568zcZjXR4RUJsZz9JHACG/YHgD1E4cTP2XG4kNistp8=,iv:9j6EfNRJqoy2xQrKrQ0ttcg2fqBFgde2sBHiUN2mJ4c=,tag:W0eyODleGKJTXe9y1n0l3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYmVBRzBtVWlrLzZnT3l3
            L2lva0kzeFgzQlFQYWt3emlCVFMzNDBHMEFVCjNvOEE1TzVGZHFPS2VsTDhuTUVi
            UzhBamcwVGRmUXl4eWJ1a1VQUzJSbkUKLS0tIHFnUDNkSUw4cFpWcTRacUovV3Nv
            VkpMZmZaQTlWT2JRektVblNGUTFKWEEKtWlpJn+NaM2xDh1T1lNQyqgv7pamDih5
            xj5ppYapMY1AuLuNmHBcANictjB7D/pIIXiuTwdvF0/eMfwZMMPdSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBbDFTT2lm
            OTArZkJZWnhwR0lIWFkxdVBoYlNSait3anYyeERMT0tDMGkxOApjR3V1VUllV01L
            VDVIdWFYZWswSVg2NkEvNmpaWmpjRVFLakdrY0lLSlVFCi0tLSBnaFFVbFE3VFRn
            dE4rMytGVEI2aC9EeGl3S2hjNm91Y1RDMjBuMm1rL1dZCqyAlJ/2KhpN4ZnXwcpj
            GDw7Pzso9TJAB/HwpF9JgQKvPTBfmfisjpM9/sTJfb0aUMnVPvyrqS7hfY7/kPRk
            gWw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZEFvdUNBTzhFeGZtWThl
            RzhZcVVvMkhtYm5VUzRydDZEZ29Iak1XbURNCmI2ODcxekNuTWgyejJ3WkhnOGVk
            YVNZY3V0L0I1NVAyVjNyZDdBczI4bGMKLS0tIDh1anhTZWVxcHBWQzljRjNiblVs
            Vy9CK25GZkF2dHA5aFZjUGdJZEVXOXMKeYHwusX/OXv3+X+ocF95X7AnQgKkGGLv
            9gbkfxndTXK4ymhhd96KGxAcDNYBYLE5e1FnVrGFs0yhLxICeutD8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T13:56:02Z"
    mac: ENC[AES256_GCM,data:R/URW59pZT5vB6YwWOSJYkQBtKgJMBb9A7sNjHSK5ob6rIf8P3mc6AxF7sBbXWsi3Ppioji2VRmfV/mCSh2qI9FLKtGGtQAqsPpTKhfQGf5nDN+8cWG3kBpwUy5J0SYVg+3rucTBDBBNBQnUim2C3qrHRKKa2+3609BexjI45N8=,iv:xtZi+NI/V5x4D2Yxip5Cckt+unnS08xd67zBejMS8Hk=,tag:x+YZm7LyGn5Oz+dVdfpbNw==,type:str]
    version: 3.13.3
