apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-postgres-app
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: data-secrets
  target:
    name: portfolio-postgres-app
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: host
      remoteRef:
        key: portfolio-postgres-app
        property: host
    - secretKey: dbname
      remoteRef:
        key: portfolio-postgres-app
        property: dbname
    - secretKey: user
      remoteRef:
        key: portfolio-postgres-app
        property: user
    - secretKey: password
      remoteRef:
        key: portfolio-postgres-app
        property: password
