apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.resumeCache.name }}
  namespace: {{ .Values.resumeCache.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.resumeCache.syncWave | quote }}
spec:
  accessModes:
{{ toYaml .Values.resumeCache.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.resumeCache.size }}
