apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-cache
  namespace: blog
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
