apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shared-postgres-app
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Cca4w5Ev2q5pVZtCg781p0VeoA==,iv:iUcZg2a6S+rk4XFaasF9U5ay3MJSIP0U5omzmJTE3GM=,tag:Xhh3BWnzg7iBCMi3LfX6QQ==,type:str]
          type: ENC[AES256_GCM,data:v0DfsxsIRuEPrXmkyEDHFKnvylFhwUet,iv:F8eZVFjNdWJpb4nZTq54ZVR2dwtawhMs8dAhPqvLfIA=,tag:RCNLDU6xeJBeaXn9Sw84+w==,type:str]
          stringData:
            host: ENC[AES256_GCM,data:n8RXHW6MpTiaf6wLDeZfjCfUfe57xVghlgvjZ91++urP8g==,iv:8Lj6yJZMwa3oPyStweUOWAtXBZy9i4qTqo5oDfs8DiU=,tag:pulTHH1CUatvvPmtj9Jbrg==,type:str]
            dbname: ENC[AES256_GCM,data:6RAGnGfRRcLD,iv:X9gZLsmftG0bsH35hUzZT7zWeGydgvAj2YE1NncRx3g=,tag:FJlXIY2CY3qXH5YsadG+cw==,type:str]
            user: ENC[AES256_GCM,data:7QJgP+whZvLZ,iv:zVtcBoBIBhVpuycOJIZ1wDOCh7I5RxQ4cVUueqRhz1A=,tag:LP/5y5ZsraajxaS2Ep7G2g==,type:str]
            username: ENC[AES256_GCM,data:exiPRh4k1LpT,iv:Mw3m7OpxFbgLMaHlGgCl6Hf0/wUgoQIlkXC95Et84zE=,tag:JlPIIkC+Lkzhd0HIh/fGXQ==,type:str]
            password: ENC[AES256_GCM,data:3jxyqfP2Bg018gpRaciwVABx6lO+faZmakagMAPpC9+HLqxvUuaT15VVLqexEMS3vRSWtUriB82pVs2aMZqp7Q==,iv:18JLOF63KUU97K7KIL+mrYR9gGzWc7g37CCac+12Obo=,tag:CVj6v61fsQhv7DiXp24/wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlo3MHNtbUU2TGZSY3pQ
            Yy90Yk03TDJ2TVpLdjdLemRoVkFqeHE5RXlzCkI5akdHY0dIM1NqRWhhdVJId0My
            bUphV2FTZk5tNnRjQVY3NThXTnZZd1kKLS0tIGxLZU5QUEV0Wm1OUFRQYmIrdjlt
            bGtRZGlhZE1GYy8yQVNaS09hMFJmS0EKYpsQQABKIg34+JDNRFuvtCSSCICJe0rn
            sIOfvmrDqMThvFvHwAkW6ntumZE2QNbsw+nsRycKvQnRLzW/Qz+cWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBclVKMTRL
            VHBMZXZyTm5qSFYxeHA4YlBOczdQeDZsTVlOMkhsdVVRQkQ0MgpVNHFzcVNZa0wz
            Um9oWXJXcWZmQUd5S3NvRVh0ZitLTXZ0TG9IT0s2Q1o0Ci0tLSByMDlCdFFhRHhh
            OEh1ZS9hQkVXSkloZ0h5L25ZVG9BbTRQYXdtZzlrVGZjCjIexz5srOYe/LVx+UaT
            vLQkur37pO0b+qcUApDDw6Vfvq7+b8gqDIrwSEOLF9mUENbI+gbXQOh5gyj22GIQ
            LkA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlRSdG13bWRsSDh1NW4v
            ZmtMMDMzT3B0bndnRjdUcjlHVEhwVVRyMndrCnQ3V1gwZ2xWVjhHN0oxZld0TmZv
            SlpnQkg4UTFhdVRFUlM5MFNiQk9DN2cKLS0tIGRxcS9iTkxabTM2dHdRRzZWMjU1
            NjF2akVJYkVBODdOZDFVNW9qZUFPaEkK9fStB6VeZKpLGOZ4iKhlnaKVsD/LOig1
            vfgIysjGYimiRkvidn7oGPKaIq59R2hoK/WOOzuBnGY4SelWv9tyHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-24T20:00:52Z"
    mac: ENC[AES256_GCM,data:7RYvRITdfuswtCHUYo/rednvvluTxEaF5RuZr+l79nBpsnK6ui5/EqQPE4y6DX1C2ynhkU6H0Gtle3E2mPhBm7fMQQs7dIPyl+CH2t191AdA5VlZ8fq6xO1lPAAOj+NObpFWRinrxZFevLnbqGFuuYNiO9CwJGXjLn5d7S39wgI=,iv:kLA1EH263Je4cZLZz74Buy9hDowRxXKXyuYz/B842Mk=,tag:WJcxl4KtW0ELKUUVbdv43w==,type:str]
    version: 3.13.3
