global:
  image:
    tag: "v3.5.2@sha256:e2aadfae709d904e87f46ba4aa49601d827b3022db22cd4d03aae816a2e7097b"

controller:
  metrics:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      memory: 1Gi

configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.guesant.internal
    admin.enabled: "false"
    oidc.config: |
      name: Keycloak
      issuer: https://auth.guesant.net/realms/management
      clientID: argocd
      clientSecret: $argocd-oidc:clientSecret
      enablePKCEAuthentication: true
      requestedScopes:
        - openid
        - profile
        - email
        - groups
  rbac:
    policy.default: ""
    policy.csv: |
      g, admins, role:admin
    scopes: "[groups, email]"

server:
  metrics:
    enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 256Mi

repoServer:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 512Mi

applicationSet:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

notifications:
  metrics:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi

dex:
  image:
    tag: "v2.45.1@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462"
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi

redis:
  image:
    tag: "8.6.4-alpine@sha256:2cc044fc5a07c9b701f8f1255a309ae9ad7856e694ac03513bf3648c01e40763"
  automountServiceAccountToken: false
  serviceAccount:
    create: true
    automountServiceAccountToken: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
