# yamllint disable-file
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
    {
      "nodePathMap":[
      {
        "node":"{{ .Values.config.helperPod.defaultNode }}",
        "paths":["{{ .Values.config.nodePath }}"]
      }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "${VOL_DIR}"
    chmod 700 "${VOL_DIR}/.."
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "${VOL_DIR}"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: {{ .Values.config.helperPod.name }}
    spec:
      containers:
      - name: {{ .Values.config.helperPod.containerName }}
        image: {{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}@{{ .Values.config.image.digest }}
        imagePullPolicy: {{ .Values.config.helperPod.imagePullPolicy }}
        resources:
{{ toYaml .Values.config.resources | nindent 10 }}
# yamllint disable-file
