sops-secrets-operator:
  securityContext:
    enabled: true
    seccompProfileType: RuntimeDefault
    container:
      enabled: true
      customContainerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
  secretsAsFiles:
    - name: sops-age-key
      mountPath: /etc/sops-age-keys
      secretName: sops-age-key-file
  extraEnv:
    - name: SOPS_AGE_KEY_FILE
      value: /etc/sops-age-keys/keys.txt
