apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:26.7.3@sha256:29be7252db0a106f1cd2ac17b9a56ff2668073da645638a38b9fc67deeb2d6c4
  db:
    vendor: postgres
    host: keycloak-postgres-rw
    database: keycloak
    usernameSecret:
      name: keycloak-postgres-app
      key: username
    passwordSecret:
      name: keycloak-postgres-app
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: https://auth.guesant.net
    admin: http://localhost:8080
    strict: true
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  networkPolicy:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 700Mi
    limits:
      memory: 1Gi
  unsupported:
    podTemplate:
      spec:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: keycloak
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
