apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: keycloak-realm
    namespace: keycloak
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:zUUZUMOMlOS0m8V5Oqw=,iv:a3v0IgtD6ra93hiLWJHNq7JrSAIqQLZ1cj55rJ+a82A=,tag:pVaMQT6ZZlg18MzAd6w8oQ==,type:str]
          stringData:
            GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Ajh7h9nzGXBh5RueqAvX1mi6X0dlbY80w0Dh3a1A5HpvteieCY3Phtp9AaIrB1qI0mQAmLO2JlD2z+876FGboCgHISF5Invs,iv:2fhUKe30+D2goXphG/Z6EPsqpia9zGZWab7fkVXpr0o=,tag:bYj5oLUE66PyXbnPJfsBwA==,type:str]
            GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:AoWIIkq1rSP+7TWWQ8XRULI20XBIMF+h3apUgfdLhgLmvH0=,iv:2lrFP/Htu8BzV83dYhuwliP2j9HKxJ6TU+AUh0BB8P8=,tag:UlQgvNwZbd9/U/rGrYmzBw==,type:str]
            ADMIN_EMAIL: ENC[AES256_GCM,data:2vwxQKlLuGLykFlLxZttcHONE3FQx0+5ZBlz,iv:hRcUOqr2kOcUlcnrAWAogYMSn8/3nj9h5XLsLtXy2VU=,tag:hjY8HpNwW/rxgFblVRP6Ow==,type:str]
            LAN_HOST: ENC[AES256_GCM,data:7rUh4n4492bldH/s,iv:pov4/U7rdCRQISm8tQzKGKusa8dMvChn/jSg4ixW9eE=,tag:cPwkFZiCZ/4CivT94TlMvQ==,type:str]
            ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:uaoujOVR8jGFDI7Jo7EABK/PpeGRL9fMAWaQQpV0l05MVtekHBgunP44+sn+mzhPuQLlgG1gM1pAxQdvwcyoMw==,iv:qPHecdJCfXgNXE+Drp/4jbovpwfyS+s05pUJoq3mOVw=,tag:037/uaPQ8S7yB6bwdKRpcg==,type:str]
            GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:T872i5/eWt3Nbvlca6DOCmw9cfi3ubu0dPieGbbrPzVB0jeDciCplFz5uCcsmbI4cf8XjMuQbi+5VybVR/4lvg==,iv:g9JDVsCUbQT347Xf3d431injIApxrykIt+0xra50d74=,tag:o90wXUhpnMPkRkaicS4oBQ==,type:str]
            BLOG_CLIENT_SECRET: ENC[AES256_GCM,data:qLIeTQYMkGgAnzopGAch1+/0PPcUmXpS6Of3Ou6sjOUKQpKBP/i67lsG5UqpnjPrhyhKYRyNRmxg84dnNKJKfA==,iv:fxUMy2TcDUbQePrFQsz165UiwCSm9YipuyEnCWA2yHE=,tag:PZm2+cgBGT2u2fJp4kLr6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBekVzYVlh
            U213V2VTUkF1NE9RWUtYVDhITHZ1YzhRUmVrelZIWDR2MFJMZQpnUWhIWkMwRisw
            by9UZzBOT3l0dG1Rd3R0N29ubGw4Q1dFRTFHaFJsY0NnCi0tLSB1QlhNb3JWUCtS
            UjNIVVluM3JkNFNQRjlrNFJWZ0picGhZci9PL0QyRHk0Cik88I3/8dKFhJ+rxKYT
            SACb5uLuBBY/4mf5XU55IjiJywRHouykgdvqGcjJN+mCPgo+kFOjCZoY8JRKMttk
            3IA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y09jajczSWZxak1YbzlO
            UE9OWDlubGpaRytnSWF6Z2pOMFdnc1V5TkdVCjRWcFZpWUZKbXVFa0E1M1dkeXBB
            MkF2T2pOZ3M1RXc0QlRocCtJWm9tNEkKLS0tIExFSEcwNkUvOTZrcHVOSm9FczBp
            SzlITVBjanVwQjRrZnBmb1pwa3dNUlEK98pUlY3bVOcyeOwT7hccgAQZsz9V5CZ7
            NwMPtDun6GEqoztSv0JfmOIOWWC6QOZctmVZ6AKm3mK5JSmb6lXPbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-15T17:06:19Z"
    mac: ENC[AES256_GCM,data:Gduo3jsRm1cZq2dnoHQuiHZSGepmmlxRBOnIbWQzN85YM1hI2ojFao0XzBeqY5HXGvIh+0pkKL/ZSkIouPy6+xroIXLso8JPDAWC2kguUzCfHFep75/12Uw6h7/DNbOBj01Ar7CjLW8IQZNuuBr2QQIJxvnJgc22xN/1Gmzpy0o=,iv:R1FFy8pZMWGi5RkV2PI603P2+mM8Dp8Uv+kkl5TOqsg=,tag:fXePfRKxYTxiRyCHNHuqvQ==,type:str]
    version: 3.13.3
