apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-app
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: data-secrets
  target:
    name: keycloak-postgres-app
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-postgres-app
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak-postgres-app
        property: password
