# yamllint disable-file
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
{{ toYaml .Values.service.ports | nindent 4 }}
# yamllint disable-file
