apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shared-postgres-app
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:9xY82m3HwCAcDpXMm0QFWGwnoQ==,iv:S2TKIM9gGH0QwpnQmKVorpCcjfYNaN8zA3/r/to8QAc=,tag:2r3Mia2PW4eiVeeZq4gdXw==,type:str]
          type: ENC[AES256_GCM,data:NGTCYWuC2FPcVdjLYFJ5g7QlpAGdcwdX,iv:boRHbHd7NIbmimrIbYs2T8t/fR+HLwskVxefLInU7pM=,tag:Nc0sU6Q2f7lCsT4uHZNg+Q==,type:str]
          stringData:
            host: ENC[AES256_GCM,data:ug7oPO38hwZrk0JDE+Sg6f+HQZcD+asOh0T2qgWLh/YFqA==,iv:6JsnCPE/EuAj5zpCyCQ53qL06d0fr1ZDU9YcLwE3rZQ=,tag:M9vB/B4qM/pYysYHyMSz2Q==,type:str]
            dbname: ENC[AES256_GCM,data:0SvO1+qKBQU=,iv:USKfZA25KRE33cHodvQ+J9wzWYKsgsMGmugEki8t1BM=,tag:SLjTpUlqQBEqFDG5y1CW0g==,type:str]
            user: ENC[AES256_GCM,data:ZWTg0mSNEqM=,iv:AzUzjPSKKUAv0WZoTpaiZq5whAnOkAgIyY901mwzh+s=,tag:EW7yL7Xkzl6o5ty9+KzOow==,type:str]
            username: ENC[AES256_GCM,data:w3ldzaxQ61w=,iv:AeVg6f/OJgC7LDzg6LxXpakfonIO8RZDJYB9fNjR13I=,tag:aSpluzqZtq+OtkRfHRf3oA==,type:str]
            password: ENC[AES256_GCM,data:oMJWbxPk6gpEZP7zohGRGbbP9XY766ZtQdnmXnv1ci69+JtQRacZBpSmbnBPzqbCqGI4kzrcE3n07MlCnHP8nQ==,iv:SN+5AOStFaPqxd+WVe8Ml774GWKmNV5QSbL29p1C9+4=,tag:16iX2gpErD1Ug2Oqc4t9ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU2lSeVhxd1NwUjNnNUc3
            bFI1YmNndG5QZHdvQmdyUGJhYXRPN1kzL2lBCmlEajdQRVM3Ymhyd2k0am00endI
            UlUzZW9iSU5vbkM4SDZQcitLMW1Gc1UKLS0tIDNTWmNKN25LMCsyOFAyNHdHUnIv
            ei9jb0NyaWZIY3ZsN0JxaGZjTlhIYjQKGq7yCyyd5lY5vVFBme3rkf6IpQE6xJDR
            dRibMmOOoNaQH5vP/RRJsImHM4/Y+xitPW4XiMKI5dW3as7XGVKUmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBMnBqblI1
            YkxlRWF1UUhzUFIwdFdnRGRqQlMydHY5QzZsZndoWTNYRDY2TQowVGhXZHl6Q1Zk
            SnFGbnBTZjFFRmlwZ2NMQ2RQM3RtOHAzeFdxenNvMm9NCi0tLSA0aVN6YndIdDJV
            TEI2Tm1wTEc2YlpsdXZ2YnBQQnE0TmpxSUYrT0hadURFCo2v1T6fp9l0SdAjmNP0
            tyVFXI+QYvqOs6sHssNPdsDS8QxTDRGc5qIV+zCH6hx1LbS9gNv9izEGBj8eW/05
            06k=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNG9ZeGpPQVQwaGYvMUR0
            ZXhDR0VRUVZYVDdxVVVqL1A2NDRvbEpTcUFvCitWMG1MUE1PVEhYaVR0ZCtCQ21R
            bldJRHRoZ1Q3dG92K0VaMXprYVVDcDAKLS0tIFJENmNDaFNyU0hDc0dSSXV6SXY0
            VVlFbk96a01aZFVSZGlWTm95eTQvWDQKMAeMmE3M2XQHbFemeMkW+52j/dIqnR6+
            Q0h6fiBsmngkzMKUylUqe75KjJt23EcmNmZRHgMt9F8BCVnCeZ0iXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-24T20:01:05Z"
    mac: ENC[AES256_GCM,data:0jVBrFB4ronXT5oiCsApeJCgWq6D59IhUT5+6R7HO3CP5MuavKF3CC70m2zF+5c79vD/HdS6rNy/f105p77TskbWsBEhcHD5TvABz/5e3YPwl4QoW0DN9Jk+dRmVzoDJHRSKFCaDMeb/oPKxgo3bfVrbkNZ+qq8eykL6aVpaD+g=,iv:xmi/+Jl8rQP6XUhm7+DH27EALPsnmWclAkubNNjBkBA=,tag:SX4g5L4JPNVkYetwijVi1g==,type:str]
    version: 3.13.3
