cert-manager:
  crds:
    enabled: true
  startupapicheck:
    enabled: false
  image:
    digest: sha256:70f532fd9cfde0b09d55687200942399d89838bc2d5d5b45152eb799a15912b8
  resources:
    requests:
      cpu: 10m
      memory: 48Mi
    limits:
      memory: 128Mi
  webhook:
    image:
      digest: sha256:a60e2dac46dbb8a7f3df95c54ce941012f54c2fe022f0ee55aaa1ab40ed957ae
    resources:
      requests:
        cpu: 10m
        memory: 24Mi
      limits:
        memory: 64Mi
  cainjector:
    image:
      digest: sha256:c85268c64f2e0e76684bf5fe8906caff34b82523561c6affe0fae3546bd87562
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
