apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: oauth2-proxy
    namespace: oauth2-proxy
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:U+9fImK3rXsn4AAH,iv:xIX5xDycyZARO17sEqFMGxH98VQ6/RqLKIQbZlJlN0o=,tag:t0YXozu69Ogld/DCsx6Kqw==,type:str]
          stringData:
            client-secret: ENC[AES256_GCM,data:mMYb1+nQC9t2SLoiSZ3HguLVC2CKom2mwec3E27iXeFtyDHUx+JcNKKk2nwUiMhD9YvGEY0AMGdImD9Zw+fbIw==,iv:FNmzGiVAu4e27uuIy5imPG89qHb+xhq0DQr2XQZsxpM=,tag:b07PT/jWkThEPm1c7FruUg==,type:str]
            cookie-secret: ENC[AES256_GCM,data:z/MAhIkvgYUd6K/VaKBt6IBqbbtFJMH2iEOl/0Rcsng0vsxIUFjuCHsjYQ==,iv:zBcmL0Ht3++pyNbNcAv5iKg/pYsegLTBSXm3eLitMqk=,tag:+HL9yzzWVHq25eFnqnXT0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUjg1RThtRW5zZGpIeGtn
            NFdTRHpIWEd2MjlSQ0UyZEgwcXJTa3hVbnhJCnlDTVZGZ2xTR2cySXVEQ1l2SlNR
            blF1U0t0SXFXeGpFekswWnBwRFMvTTQKLS0tIEJJRDV5Tk5YMGVDMWNCVWRGQ1lU
            MVBNTFNpNXd4eElwY1pXZjF4NzlPNzAKIRJrpaLUQqpnPsqdrRqnbrDdfEYfoQsI
            aCTrAhiXg9egHTiwy2bPhU0WfptgQvwiHC8n1MnhDyxPgV0j1ywpaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBb2hGR0J5
            VUxTZWxad2xIZlVLcXhFS3VFR3JyUU14cTFsRmVNY3FPYkRJZApOTXRiclJXZGty
            RDRwM1YxQVJsRWJESzRicW5vbEc0eEhPblNSdnNFek5nCi0tLSBhUmhPTWZIUHoz
            RkFvSzhkRVFKakFFODJYMXozcFpjR2hvemxJYVR0YThJCidNYhWzcgGXmdaQzJl5
            JBScDs9vo8xekK7Nx0QUaaNy+SLGK4ZoSNbECNBqaqqSbiEYYgNORWprNMAlRSUL
            VRM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNTVndmJISGtOTVpXWVZH
            WE1Vbm5Jam1TRzFMZG5VejN3Um1Rd2hhTDFRCk1GdFFkSmdzazBGaWkralpWd0xX
            ZjFtS3lPYmtuS1N6eTFoZ1N3eEo3bE0KLS0tIDE5ZWZOMXNEZlNIaEhvdVFNdHRR
            UXRRV0o2ZlBHa2xoa2RwNWdRb0xJaHMKFCPvI40uJjWzvgWh76YmOSxfqJtVJdvU
            UmbDxW9dqTdkXqE1VXCHRdciA0BlTYPKIksOgjFN40EiDp+QZ58BPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T12:47:25Z"
    mac: ENC[AES256_GCM,data:FDTZwWBVP7697AxsiQX+70mSyn98J0vhxMCyxNUz7KjAt+3VzLElhiqBEv58oxV6GGsuORZR/R/hlYAAEAEW/lbBBxTOQ3MatxqfNMe5RHR1w3TlK6mEVBWD6KFv7Hv8RzJY3CKoa0ukO/HZvBJKbDrfqSmzjyXbOLUuT2mSrR4=,iv:+/rzl9NboKNw0tvYYr6a68CACcZIImiCW8RYUl55w9k=,tag:7EJ8EwV1GjCDoomvJulijA==,type:str]
    version: 3.13.3
