apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  source:
    repoURL: https://github.com/guesant/hl-infrastructure.git
    targetRevision: main
    path: argocd/apps/platform/admission-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
