# yamllint disable-file
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  conf.yml: |
{{ .Values.config | nindent 4 }}
# yamllint disable-file
