apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:BSDGLd6tg4XcHX9+kfMaU022,iv:O59wm5PPRwHDBmRgph1BHGHjCd7a+XGVKSYt/1ZmVEM=,tag:i/4S5GSngGXvkLAytJ2WeQ==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:wozEfMlYffEc2KyNN3T7iyZODtBHjad48w==,iv:BmV3kxOFtK0wdEqmBMIbMbHspoU2OeCOATzFHicPx4w=,tag:HDsE765fDWhbMMyrjWDgsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBMWNxcDRF
            aDNlSks2TTV6Q2p2Y0RpUmZWL2p2Wm1UbXUvZXBXWEtXaSt3SwpaR3FOa09rNnhn
            R0dTUlRCdVNYN21nalRMQXdJRW5PTHhWSlZiWkpFZTJnCi0tLSBsbjdrUFJZQUVN
            QnBLdVRhLzJSbXJjSEFLSWZNaE5ndjgzWThyR0VrTzQ0Cko/qiQrQeCs6uuq46bM
            m+a3VX2RGRVrhRbLTp281LKEh3A3u/To/leLgKRbZKDZVSn+w4KqtNQOIgPTa9Lc
            vsI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa2RzOVYzeEY1QXNaZEZM
            MXFIUTZuYXlub3JDTEg1YTZ1Uyt1K0tjelZFClNTRC9kYzdzdzZBbHc1OWRlWkl4
            WkxuSDM3RW5Fa0x6ZlN2Mjg0MHZXWncKLS0tIGFBMWRmSVlhNFNYWE5zNVZ6dkNK
            UzRTNmQ4THRLOXBWWG1YWGpUTnprMFUKxVVTrFTgPj2X0AXAxsLJVR5pLIzvlpi+
            IJXKmQEton40VUjZBrHRC3TmGraFdMZ+CKPUPnctjPiKhMw8jjbToA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-14T21:14:52Z"
    mac: ENC[AES256_GCM,data:fi22ygMW5I1usPLjJ9RZOLtLXdPkP+6azPP2YCpiV89peHC0UB2qZ7EBGjMo8Hf8QR583s5WVOtwZ25WSHWebqUiWRnznqtWYJBv7SpDvtJGk3Zht2fB+MVF4HQ02nJgT7zd/KuU1dgUBLb1BPifPOnOJPi3pj4VdkJvQsGQTSE=,iv:bLlNLowvrkKUAdGVY/t8iSm6aMI9TLHbKH1iuRlST4o=,tag:4Z4bG5kkpeb/ZEXwFvrt+w==,type:str]
    version: 3.13.3
