apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:BSDGLd6tg4XcHX9+kfMaU022,iv:O59wm5PPRwHDBmRgph1BHGHjCd7a+XGVKSYt/1ZmVEM=,tag:i/4S5GSngGXvkLAytJ2WeQ==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:MRSv/WwCBOogLniHpRaKogVbh+4aKnQh2zCNDqtlEQ/1hfjKEuTejB3xp3axiRUHwQGwjdoFJ+LO7fjz04HUPu4hvEB2midW+rrPBO4JzBBDtsC0pfc9DmB8bzf6HDO4Mj6/r3fybQR9KJnUwf8cHWdEQRVa9yhVTlKbEy+KVZK3W3NGz/mGFLbfWhJqj0Epu56ScRXgZ/eBBrQucLZPGVbcN+IoimHc6oYqZZBnu+k/FxgnODsGNtXg7EiN8/YYuwStzgw8bP9R4A4i/Yuuh9wom4kvcXAL/ATXvMGg4a2k0qhwHHe5FvWB8cj0RUO8,iv:phg31L+OjsSXlIzJs83BCTfSDfjRFRy2o1LiusojOZ4=,tag:Iwh6absQjYjkGcobgVu7jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBMWNxcDRF
            aDNlSks2TTV6Q2p2Y0RpUmZWL2p2Wm1UbXUvZXBXWEtXaSt3SwpaR3FOa09rNnhn
            R0dTUlRCdVNYN21nalRMQXdJRW5PTHhWSlZiWkpFZTJnCi0tLSBsbjdrUFJZQUVN
            QnBLdVRhLzJSbXJjSEFLSWZNaE5ndjgzWThyR0VrTzQ0Cko/qiQrQeCs6uuq46bM
            m+a3VX2RGRVrhRbLTp281LKEh3A3u/To/leLgKRbZKDZVSn+w4KqtNQOIgPTa9Lc
            vsI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa2RzOVYzeEY1QXNaZEZM
            MXFIUTZuYXlub3JDTEg1YTZ1Uyt1K0tjelZFClNTRC9kYzdzdzZBbHc1OWRlWkl4
            WkxuSDM3RW5Fa0x6ZlN2Mjg0MHZXWncKLS0tIGFBMWRmSVlhNFNYWE5zNVZ6dkNK
            UzRTNmQ4THRLOXBWWG1YWGpUTnprMFUKxVVTrFTgPj2X0AXAxsLJVR5pLIzvlpi+
            IJXKmQEton40VUjZBrHRC3TmGraFdMZ+CKPUPnctjPiKhMw8jjbToA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-15T00:43:47Z"
    mac: ENC[AES256_GCM,data:y1Y9b9cMPjQ6cOJsHAvibpnQYhM7yMVGUquNs01Zvl8jiaPQkaSLMPEPhc3tmoUriXuaTI+isFssmw7lvaaBIGyTvikXvAWJdoQMuRQKbptWgsHGuoywqDjqi00oPD1D5u1qZaGqlpUTajvkSFFxvtBhapcuqKWYCQe0Y50at20=,iv:m7pFtI5KSVF++cfVrcoXsSMV6GPQ4SmJKN2J296hQR8=,tag:Oci41s2Uzh8xMX2YWT7qLg==,type:str]
    version: 3.13.3
