apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:zGcwfOxI/A0+nMeJ1824yFF0,iv:cuuGX6KtvbB6kKwQwyFvgzIYrnW6hmX4PtVCosq1SA4=,tag:eBJrMHK1Wo7/W7/oCiQtOA==,type:str]
          stringData:
            credentials.json: ENC[AES256_GCM,data:xSAWLjRHzeJ/S3G85dESaD9qQph5QEg=,iv:n0UahiM/3TLIj0SW3P6nFaej/f+uGLXaeFU2/A5YDBU=,tag:SAz48u6oyY5fi96zSZblhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBc3NCMy9m
            MW1vZVMyWUk4NUFic0t6ZEF2clkrbVBqNTg4N1B6dHZxY0JGcgpxZUtSVElUdGJK
            anlRdmNlQVVPbUtZOHhxQjNsRDdNMytHbnJVeDNHMC9nCi0tLSAvNVpOV0ZrNEZB
            bDlhR3hVNXQra28zbFFQeDFmV1VPWFFYM1ZjMCthcEw0CpUmKawovWynvQ59dNgA
            eI3odQ970N6PtLw7hCFQFRJsOheApuzwqX1N630kko+LHSGADZxL6Uw4XmsOW7hh
            WvE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOTVzR2V2bGVERzd3Y1hK
            RHllWVBLd25oZWtGR1g3QUtQWW1vaCtib2g0ClFyNHBCVWxoWlAzVUdTbDM5ay95
            Ny9uTDdwSTVZTnZtTktFbURBOUFJTTQKLS0tIHk2VlcyK0F4VmUyYWFnUTEyZTBq
            WWxGY2hSOU9uL0h4R3NoOVpjc3RSMkkK7YxA16JioIN7i4gLc18d02Em0f2m8Zbr
            sdpuLGBR6IfiV4wkFvXluOv75tyEYSHCz9oQBahKThHcXCNsbqf7QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-14T17:44:04Z"
    mac: ENC[AES256_GCM,data:wmI1KK8X/OMjUopgZopDIRx7ULdSkIRgMEH+zDqj8srp4IkLazwaqrl0kqhhn+7b1Tvx8UaUx36VCL1Omfbsg9gRHxWQGRyFUeDoXH6OaOt0ALcKHWFj5KcrW1Z2769IvCOQZltdp+i1RkoY+rP4476WXVzkJJFClD6UnC7fWKM=,iv:JLsUBH60PiE+hGnkJjvBciH5qFiq9DQwoHQjYJvPZW0=,tag:LkWcA4tjeVcUB7qsOK6TbQ==,type:str]
    version: 3.13.3
