apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-oidc
    namespace: argocd
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:7kbxdoURw/95V6M=,iv:VVhb31rOuCYig50/TNCmN5afY4OBaUzDDGzVQyA9Fnc=,tag:2mhPH0SUkivpgjxDM+rnGQ==,type:str]
          labels:
            app.kubernetes.io/part-of: ENC[AES256_GCM,data:1pAZavZ7,iv:usjrV6YHGBGFlZkqjFG4oypoS1OZxPTyp+FyPsIoN5Y=,tag:Gz201YUgYMgxvgYCi/tx9w==,type:str]
          stringData:
            clientSecret: ENC[AES256_GCM,data:jeiCCtoxDA+oEehvMGicuezmKV4bqOxhoedU5YegU1Zuf3+gzhnnibZ65yD+oj46n/TD0tFCc/xWzuTIu0+BXg==,iv:vqCbBeD+18QpClzDhx1gtlxEqzB3tauVA3gxp2u8wiI=,tag:iwm4RjOnCx406PtEAYQ4oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaWhGNVNNTWlSL2NxVFMy
            NFQzaG5IUHExWXB5U0xwU0Y1dE1rNncwMWg0CjJxNS9Ic3M5ZVo2ZGNuMWRRZkFP
            MkdjODJYM1R5YTVKUkFnQTk3aEdvcVUKLS0tIDN2Tll2QU5pVkJNMlVaNmp6ZEJS
            Mnh6eHhxVVkxdzdwTmhyUFJLOFVPbDgKgWIBXBd8NEajTlXBJEhg6TqXmkK2RIQ7
            +7rLj4pbl6BLaqd/7lNkpG56ZEQyklUAn0e5UZABzIX6v4JGOcCiOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBNWw3NElS
            cTNKYVM0bVJHbk1tbUNQK1EwUUtPdkppSmZjbWF4K245SndjSwpLeGUvMkFZMjNB
            Z2pmanlKeUljUmFlOEVzQ3VXODBZNXpCMldWY2Q5UWdNCi0tLSBNOFRndXpsNDZx
            RUNqbkhOWWhGMVQzY3R4NWx2TVVneURpV0kxajF4aUtRCkDo7IfzDqkGBOOLau7K
            9TCX8OqXSx2qts/h6KvnJKVCQjH3CMvc7GUpLfrC0DOhS32gsaD4bfFT11Uutz/+
            hnE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WGswUDg1ZnpkdkVCU3dB
            d1hqWlZMZG1ZMlUxcXZuNXV1M1Vlc29FVmg4ClVwOHBzaXg3S2JhNmEwTDdpYUpB
            VUxoZlRZaFF2aHIyRCtkVlBDRklsN28KLS0tIFBYSVRNdVZOTmk5czhXanZ0NCt2
            WlE3UFpCQzhmRG9KdlQzNkdLUm9ENVEKOAPHNV5XEGMiiGdvai5xNk7eSvOGG4Hf
            yBVGeEvxa6vmnqBfuZItwgHfEfOXMEoH78W1Dn1PiKxFgAkCWTJCbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T11:27:36Z"
    mac: ENC[AES256_GCM,data:UD217ogUYBa9ekqoTcIpwJ54HIYb9vvEoQheEmZJlOJWs5Do4rwqSJx2WKHOSNgxWUqaHIhO2/IN0I2nqQpKKHpvSKj6C53gGP7g87RwslpoNgg7s7yU41TCJgQ18r6OcjioRkjGt51cXHjQglmtJOQ/9qxNntDs3NRYbBmZXHQ=,iv:sfHaLFFAxZ7few0Umk4EhMIsiEJrQgsF92MI9zRa0Cw=,tag:lMDcVWaow7ZX+UT/IZCpOA==,type:str]
    version: 3.13.3
