apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-oidc
    namespace: argocd
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:7kbxdoURw/95V6M=,iv:VVhb31rOuCYig50/TNCmN5afY4OBaUzDDGzVQyA9Fnc=,tag:2mhPH0SUkivpgjxDM+rnGQ==,type:str]
          labels:
            app.kubernetes.io/part-of: ENC[AES256_GCM,data:1pAZavZ7,iv:usjrV6YHGBGFlZkqjFG4oypoS1OZxPTyp+FyPsIoN5Y=,tag:Gz201YUgYMgxvgYCi/tx9w==,type:str]
          stringData:
            clientSecret: ENC[AES256_GCM,data:jeiCCtoxDA+oEehvMGicuezmKV4bqOxhoedU5YegU1Zuf3+gzhnnibZ65yD+oj46n/TD0tFCc/xWzuTIu0+BXg==,iv:vqCbBeD+18QpClzDhx1gtlxEqzB3tauVA3gxp2u8wiI=,tag:iwm4RjOnCx406PtEAYQ4oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBNHhpR2Zm
            dEtKWVZPbFlvem1DZDBhNngwT29oUFl6UkJVSWkwV2RYZnFnMwp1V2pYeVdDb2Fj
            Y1ZjcTlYSklDalQwVFduZ3pqTjNUV3FRUWJ5bEUxMXN3Ci0tLSA5UWRzQnNnZ21k
            SUxDVTNGcE53SlIxd2p4YWRLYlE1N1RNMmRaeVFtSDFrCgKzh9LQK4Zb+G5xFpsQ
            IYDJoSZk9j6UoneVsMHR0k8qBNn4Ul6Ji6G4xh1dWoTP6l4bOkPdwsIwqmzw3+H3
            IUE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTG9PbzA0N0piVFBGejR2
            K1RBZmZpV3Y4R1d6ejlDZkpoaEJCSW5UaFU4CmZjcm1YQ0dONG5qOFB6ZFJYMUpq
            OGlqd0Y3MjVIZFE0UGZYd1Y1NmxENEUKLS0tIGp0bmlDWU1VcWpkOFdMbXF5U3dN
            KzdxVUwvTlhJN0orSkwyM0Rsa0k1dTQK+VbUsp7ds83G1PVReB/kYrso4yIwohLt
            GyXYmnZgV8FZIOZLueb0+CV4APTIdHm8/APT2+I1EUzP3yI7rn47Qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T11:27:36Z"
    mac: ENC[AES256_GCM,data:UD217ogUYBa9ekqoTcIpwJ54HIYb9vvEoQheEmZJlOJWs5Do4rwqSJx2WKHOSNgxWUqaHIhO2/IN0I2nqQpKKHpvSKj6C53gGP7g87RwslpoNgg7s7yU41TCJgQ18r6OcjioRkjGt51cXHjQglmtJOQ/9qxNntDs3NRYbBmZXHQ=,iv:sfHaLFFAxZ7few0Umk4EhMIsiEJrQgsF92MI9zRa0Cw=,tag:lMDcVWaow7ZX+UT/IZCpOA==,type:str]
    version: 3.13.3
