apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-oidc
    namespace: monitoring
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:lnZx8MDQEcGCzisw,iv:DavaHsL4JZgq74xpbqM99ZaKQaVShDapzuzyATOkzvI=,tag:omyuqiUTH/P1S3kPBNNajQ==,type:str]
          stringData:
            client_secret: ENC[AES256_GCM,data:P/gT2veUMX5ifXbzfoIGajhofD7D64w6yXzJAceYp0b4ktTZDlJomNycppQtM4H9lBe5MSiwfnWwptocx5F7rQ==,iv:63qJM0tJWBwyxSXCBk2AGcuiaCOjJWb5lo4FZEEDoWM=,tag:0b2F648Z4u+KXHrjoR8m1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L1ZLalVnQWZPS0ZiWUsz
            OWs3MkJhVWFPVUFMTXlsdFpBRGIvOStXSFNnCkNNblQrbmZIaEs1eEVFQTRQVFhm
            S0F3Y0FTd1l4TDhaRGxwc09aZzdKZlEKLS0tIG94VEpxN2w3bXhwa1ZOWGpTVXph
            aXBGZ2pCNCt5RmhHb3VpNXY0Q3VJQWMKyK6J3QbRzv9OgyHrbU/PVnc9SElELYFv
            EYeEQEWS/nbGP9Rugi+r7qwuqBy7NAF6kbkNg1xEE4/kTge+OZCzOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ck4e72lx0phuzzspnzynah67ep7e39ycj37g2h9ds4k874wapvns30sqr3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBMWZwQnpR
            eTNPN2MrcWM5U3dqV1lsWkhTM3hhNGFMN0J2dG1wdGpHK0hwMQpSQXZpZlYvVm93
            Vmx2QWxtWWl3U3F5L3hOeTFoNUs0RU1Hd3NXeUcxOGxzCi0tLSBxZzdTZGxndDlJ
            WnBucjNhVUhCc04yT0NCK1Q2bTYvc0NJbWhuNlRjK2Q4CtRlAGQ9Jayix+mN6r4g
            uj90Il6bFgSIZl9Pm6CLrQ9IJD1ySrKc+YBGBA78rqkXnOxbFsGC8BGB7rL4+Ic/
            IPc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ05GdktldGt4S0RSeU03
            NUdqaU9MdUZBaEdFdEdYTmZCdlFNSVo0dVZJCjUwSEdyT25sSVdUdjFCeHVnUHRn
            NEp1eldJY0lZMUtUdWYzZ0N1elNMZ1UKLS0tIE9RVDZSdERpc1U3eUhhOFovY2VC
            Ulo2R1d6M250U2dTaGlwV2JsbUJ3NmMK2A0PkGm/Ae+HXdwxcpr53ysyWdCa+mYQ
            z07TkfWqlMX/bQ1oN0v86BwId0XcC0zzody1daYazoV7HerHuKl2WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T11:27:36Z"
    mac: ENC[AES256_GCM,data:VFL3qAXYHE5/DpE3bPimwGZua6euOUSLh0f9C6LkqydYIIx55oDazNi4il1QOEIk54tUIUuv3j8Yfuj6qLy+0XnOHEcaO5XtUbiouSQN7FQLg/2RAUQfCnv9wOIZ6E/Wlb7Sw93JoNvTGRRKik7tsucyhV0fObYW41j5jEDJIrs=,iv:RxQykYgZWYHRtuxcdPzakxzkWEpHNmbH2N5tSTGf4Y8=,tag:2GVg6VQ4Zx/ZwxOw+2v/mQ==,type:str]
    version: 3.13.3
