apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-oidc
    namespace: monitoring
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:lnZx8MDQEcGCzisw,iv:DavaHsL4JZgq74xpbqM99ZaKQaVShDapzuzyATOkzvI=,tag:omyuqiUTH/P1S3kPBNNajQ==,type:str]
          stringData:
            client_secret: ENC[AES256_GCM,data:P/gT2veUMX5ifXbzfoIGajhofD7D64w6yXzJAceYp0b4ktTZDlJomNycppQtM4H9lBe5MSiwfnWwptocx5F7rQ==,iv:63qJM0tJWBwyxSXCBk2AGcuiaCOjJWb5lo4FZEEDoWM=,tag:0b2F648Z4u+KXHrjoR8m1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBbzhIWE4x
            VWFXT1J3enMyaVNuNjgwNmZMeWtQcDVIMzFwZUdsaU5CNHYvNApaZ0FuUnd4OElV
            VE9aM1d4NGZRMGhJS2JsNlRkS29KWHY5UzNsdlZJVUtFCi0tLSB5TVZwS2ZpTXk3
            MzV5bzc2eEVaVHIrVXVMdzBCN3JGcW43eURhbUFTTFlrCnB7BOH8QwPiEtQM7hZk
            KwXPG+mQrfb5Smb9Ukg5RGIU4lv1/NmeqganIO1NFQHLwHUx+5CZbNN3wOKZflwn
            RP0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMHhCcGR4QnMxU2FYZHNC
            RjV5RUJSdkFVK2lxeWJHTi9FQWF3aEJycGpNCmg3a3UrcmhlQStaMjI1T0t4eUFh
            NTVoRHMvTDlFL2t4eVFZU2R3VG9KRVEKLS0tIGFhZkUxZXBOUUM1c2VSZkZKVi9Y
            Q1VuK2lYTm5ZZkhzR0JFZkNSMFhETW8K7mSWAxbapBZpHJ5w6atnlgactWZUpeKN
            /VvhwwFTUIp6J54g3g1RHVeHtoRZnsKw0KXYXoAxAODIj6thn6ouaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T11:27:36Z"
    mac: ENC[AES256_GCM,data:VFL3qAXYHE5/DpE3bPimwGZua6euOUSLh0f9C6LkqydYIIx55oDazNi4il1QOEIk54tUIUuv3j8Yfuj6qLy+0XnOHEcaO5XtUbiouSQN7FQLg/2RAUQfCnv9wOIZ6E/Wlb7Sw93JoNvTGRRKik7tsucyhV0fObYW41j5jEDJIrs=,iv:RxQykYgZWYHRtuxcdPzakxzkWEpHNmbH2N5tSTGf4Y8=,tag:2GVg6VQ4Zx/ZwxOw+2v/mQ==,type:str]
    version: 3.13.3
