# yamllint disable-file
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.configMapName }}
  namespace: {{ .Values.namespace }}
data:
{{ toYaml .Values.frontend.data | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.laravel.configMapName }}
  namespace: {{ .Values.namespace }}
data:
{{ toYaml .Values.laravel.data | nindent 2 }}
