{{- range .Values.satellites }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}{{ $.Values.delivery.namespaceSuffix }}
  labels:
{{ toYaml $.Values.delivery.namespaceLabels | nindent 4 }}
{{- end }}
