{{- range .Values.satellites }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ .name }}{{ $.Values.delivery.namespaceSuffix }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.delivery.projectSyncWave | quote }}
{{- end }}
