{{- range .Values.satellites }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ .name }}{{ $.Values.delivery.namespaceSuffix }}
  namespace: {{ .name }}{{ $.Values.delivery.namespaceSuffix }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.delivery.resourceSyncWave | quote }}
spec:
  promotionPolicies:
    - stage: {{ $.Values.delivery.stageName }}
      autoPromotionEnabled: {{ $.Values.delivery.autoPromotionEnabled }}
{{- end }}
