{{- range .Values.satellites }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ $.Values.delivery.stageName }}
  namespace: {{ .name }}{{ $.Values.delivery.namespaceSuffix }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.delivery.resourceSyncWave | quote }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: {{ .name }}
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: {{ $.Values.delivery.promotion.step }}
          config:
            apps:
              - name: {{ .childApp }}
                namespace: {{ $.Values.delivery.projectNamespace }}
                sources:
                  - repoURL: {{ $.Values.delivery.repository }}
                    helm:
                      images:
                        {{- range .images }}
                        - key: {{ .valuesPath }}
                          value: {{ .imageTagValue | quote }}
                        {{- end }}
{{- end }}
