apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  source:
    repoURL: https://github.com/guesant/hl-infrastructure.git
    targetRevision: main
    path: argocd/apps/secrets/operators/sops-secrets-operator
    helm:
      releaseName: sops-secrets-operator
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sops
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/audit: restricted
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
