apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgres-backup-credentials
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretTemplates:
    - name: postgres-backup-credentials
      stringData:
        ACCESS_KEY_ID: REPLACE_WITH_REAL_VALUE
        ACCESS_SECRET_KEY: REPLACE_WITH_REAL_VALUE
