apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-backup
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  configuration:
    destinationPath: s3://SEU-BUCKET-AQUI/postgres
    endpointURL: https://exemplo.invalid
    s3Credentials:
      accessKeyId:
        name: postgres-backup-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: postgres-backup-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 30d
