apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-backup-credentials
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:b3fqxrrzip1+OSnQSTofP7GUl7zXT7uep91q,iv:8DXoB5Vg65smnxhO4khIzqeHgYTzpbSDDZTiReLdtEs=,tag:9xEWJQRDGt2bL04NJWVIzQ==,type:str]
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:NLs1P91xmbWpl/or0tsH9PkGMLTDPl0=,iv:g4OBZ7uHXgG2MwYrzdkdZVmcF6N7Jd+tUKTjH/Np0bY=,tag:wLvuy2M6KO0zDVYvge9qVg==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:FDec9MOIDCEVt+GqlTi5dbFKGfxUGuk=,iv:13dQCiR9x7qEt2y+a6ck9l17m4Epr+cFrEmpn13onI0=,tag:hhS1lieVH1OiY3fPhm70LQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBK3RlcFFT
            ZUY5aXEwRk1zTVZWQ3B0S1loM0pGeFRkYm8ydXVBNk1PcEU3QQpSUGZlT203L21l
            SVBENHFUdy9qMzAxY1ZGNGZLWUJuQ0M1dndaWE1qUjZNCi0tLSBjMTdLNCtQQ2RM
            YzF1TjNPTnZ3a0EzU2RlbjVONEJoUUc2eHI0Y240WCtnCgQzkX/KPkytswrIIAQ2
            3J1pwsJ001FZ5YV/6Te/4Ay2Dza49teDcbKfT92RdGr3Y1f6iI10OYFYovihKQMY
            PPw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGlnb2Y1eExTdDJBOGk3
            dDV1MmE3WXdHNGg5WDM0RHNTTFhldW4vQTBRCjRabGxSamR1bWpwaWljMGtyNFRY
            ZHNDSHJib2pxVWl1SitsS0I1Q1BwS0EKLS0tIGNJeHBxLytxbUROY2kyWEVTb2d2
            Zm5YOCtNTXlmR0FmaDA3MkRqbXpYN0UKorP3PzI7pgwZ+3xxa13uGONspOTjaRIC
            kVcvGXCVePK2SA0xZ5WW4uD7J2LT1uamC38NuuRqIJClFnRVpOauPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-14T17:26:13Z"
    mac: ENC[AES256_GCM,data:3VDBaMCwyqriRPQseJzbXon9km1iUwSx+hZ+XSXRGaLkdry5AzVbmI16XPdyDsXdergVmB01/RZG5hVT7eZ2G2w1D1jeVjQAC0XMT/mA5MC6ITN/ZUSO35HZE/r+j5AmtYYxOZ48Q8zOugkslQw7GfaefrZLJPdARkh55aslQOE=,iv:+nQZnxNTAHq1Sj5SNvBIPRDtvH6VK6lxekQIsryqMZg=,tag:SYTLqnNrLFA6mXvAvjRGmA==,type:str]
    version: 3.13.3
