{{- range .Values.satellites }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "10" | quote }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  project: satellites
  source:
    repoURL: {{ .repoURL | quote }}
    targetRevision: {{ .targetRevision | default "main" | quote }}
    path: {{ .path | quote }}
    {{- if .helmReleaseName }}
    helm:
      releaseName: {{ .helmReleaseName | quote }}
    {{- else }}
    directory:
      recurse: true
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .destinationNamespace | default "argocd" | quote }}
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
