{{- range .Values.satellites }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argocd.namespace }}
  finalizers:
    - {{ $.Values.argocd.finalizer }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "10" | quote }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  project: {{ $.Values.argocd.project }}
  source:
    repoURL: {{ .repoURL | quote }}
    targetRevision: {{ .targetRevision | default $.Values.argocd.targetRevision | quote }}
    path: {{ .path | quote }}
    {{- if .helmReleaseName }}
    helm:
      releaseName: {{ .helmReleaseName | quote }}
    {{- else }}
    directory:
      recurse: true
    {{- end }}
  destination:
    server: {{ $.Values.argocd.server }}
    namespace: {{ .destinationNamespace | default $.Values.argocd.defaultDestinationNamespace | quote }}
  revisionHistoryLimit: {{ $.Values.argocd.revisionHistoryLimit }}
  syncPolicy:
    automated:
{{ toYaml $.Values.argocd.sync.automated | nindent 6 }}
    syncOptions:
{{ toYaml $.Values.argocd.sync.options | nindent 6 }}
    retry:
{{ toYaml $.Values.argocd.sync.retry | nindent 6 }}
{{- end }}
