sops-secrets-operator:
  image:
    tag: "0.21.2@sha256:7bba7083dfa09d2e46e40f106af16f4f590165eaec862d6fe1fd7e65bb763faf"
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 96Mi
  securityContext:
    enabled: true
    seccompProfileType: RuntimeDefault
    container:
      enabled: true
      customContainerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
  secretsAsFiles:
    - name: sops-age-key
      mountPath: /etc/sops-age-keys
      secretName: sops-age-key-file
  extraEnv:
    - name: SOPS_AGE_KEY_FILE
      value: /etc/sops-age-keys/keys.txt
