apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: portainer-oidc
    namespace: portainer
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:fik496/OZItBsyZJrAU=,iv:1smwA6U7uDYSlFqScacU4pRntaM6Dlj52+g6pRT4LiY=,tag:rHyndWrsxtc9yfAC6hie3A==,type:str]
          stringData:
            client-secret: ENC[AES256_GCM,data:OsbPuYeS1Ch5o+OvSBQe3OyOTa2t8rslpA39VocmJgIfXunIHrM68Uo1s0mefArNg4mTtJppRbqxcEe0/lLOjQ==,iv:T6wGw4pK0TRblnrVM16gCUKK3J4LSwvQ+9p+h/Isqw8=,tag:xIivW3ucG32eRqSbmhbnAw==,type:str]
        - name: ENC[AES256_GCM,data:PDiUtxzOSuuDQZv2VuIh,iv:JICU6z9q7miiU1BQJvXGo+tkkBkmAvxOonyE/wrL/74=,tag:MMf/Gkb3aFGm/SbQtrdpjg==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:S6+k1h4lFgCEoIGbp1LmbUf5y/QS6OxqzTwH4dtRV7qK6vOrK86v6bx28DpFY4PW,iv:jdnoym9nFbMlhxTCLLnKFQpDDPQYONVBtflLBhv8O2c=,tag:VQ3vjSGFk54tgorYQJ/h5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBd3N3QzFs
            b0crdHUvTGMzZXRyNk1mc21vUXh4WGdWWm41ODRZWk1jVUkyQwpvMTZ4SXk4UFpz
            Q2RWWFpIVENleHgvV0xwUFY5eU9xN0VJZ1RmTDRDQ0pFCi0tLSB2U2hpQjdDOHZF
            bUFtNXIySUpPcnRsWWJYdnJqZHdmRExLZzFORlN3Tnc0CspeJaMY/V6JJMCvE1I9
            J03akfGk306PKIibI6nKbLDj/3o8lKsrk744MVAeXkY7d6ybDEMwSj9CHQTr7R9L
            wao=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRjN2V1ViSEdVYktzNEJw
            Z1hjekQ3Z2xZc2RkMDF6MjBCekYwZWdBT2xZCjkwbktBblp4b3dhQnN5UHV2ZnJi
            L09LaE1XVFZVbVZkMnB1WnB2L3FjeFkKLS0tIEQvTWlxemNLWHBmcFhseVZwQWwv
            NnFDTE5mOHJES0xoeVRPNzhYR2RSbjgKL8c1hWaZ1A+eNizcPjeSHUpq0cD/IUVB
            L+W97YZdQ6PeT2q94JwNacJGATDBlpCDXQrYAe5TSzFRztYehdR+Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T15:40:05Z"
    mac: ENC[AES256_GCM,data:KywNFeNA38brkfh3Lmtj3JA/itFIjHnKrIlg1aU5LFtOQSR6yKJ+nwO5zcLrAeM+ItQ/VFtT27r77KChFtRCK93NvZmiiCa/Fgy13qFc5k/Ye9P5yAesZtn5/6PuLX6IdmxFNc4MssmfHWEzNYl5Vu3xoogCyJYKBntMvWNH6gc=,iv:DB+kEagPolngrhe8Q6CRBTyMVGRDo//T/dJK1ExhteQ=,tag:onabbRF26kyNhbui7CySjA==,type:str]
    version: 3.13.3
