apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: portainer-oidc
    namespace: portainer
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:wAhKqxn6hhv2yvkudsw=,iv:Q7SMFKyHZ884sW9hk1j3ZNAVuMTZM2xYrYfcKCVmTK4=,tag:nBy7DxdrUHlITuyAfRuwWQ==,type:str]
          stringData:
            client-secret: ENC[AES256_GCM,data:cwcKemKKieMfzGWT45XTPigOOOTV7C+cmchtGGtUaxSTipWB2igyf+AJpAsVSQB2Nw+SDCUi+yjiBylF+RhCrA==,iv:CsqpB8iZyqbf3V2C+tdHySmd+mWmARzNgQfEUCRuC3s=,tag:KYr3XjDwwauS0rXrco72kA==,type:str]
            admin-email: ENC[AES256_GCM,data:1SfoUlm3W2WgIjXgKx9G/0L1sJp9AgXopW7q,iv:zINp2LX84YHuBNafk1HUUBUogTlBaNVJErhNyIKjiOc=,tag:L45ieqoX+tBaNwz3A1GmzA==,type:str]
        - name: ENC[AES256_GCM,data:MKTA3HsZlACVUbbFV1ey,iv:ssBFaqgX2r9LqZ1tAwHWaIK/9Kexejj+d+NJLcVnAS4=,tag:R7N8AfjSi9ePP1d+77vscg==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:LffSqh3L0wQDaCJP1fvzqdxn//s89BwW6nM18uCLALVv/KGlrX69uF33zf4a4F0a,iv:zJD1uXQUioQOB3Rhm/8oezUqEJ4iRNUxueM2+JzZ/3U=,tag:cLXpJqA77zXQOqwjrU0dlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpWc1FQUSBBNjRvR1BS
            OWRoSFRHTXFwTHZlRVZPUVU1N0tSWUlrL3FwTDRNZjVONEgzQgp5V1ZLd2dNVGVN
            OUI3dFRFZXhpZzlVam0yY1dRUHdlNDc3aENTanBpRXM4Ci0tLSBBMXNld3pWckR0
            czUxS1VTbHRwcUc1M3hvYmRCVDVrSGQzanZsNElwTmJJCqevDJcV/KReojM8R6Lf
            hT+6wq5GVjL38O94aQNrbpzkB4kjyrhQQGqi6Jhlk2d5d1Zb5mLfuziRfmFARCM+
            PW8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qtst37zx9f0t3rsvcuhvfxx7rd67xxmy7nqp4m9ntrgycu0klgygvs3vkh8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb29RZ0JwVjJLUi82YW1S
            amZXVTlmcGo1OGYyYjF1Q1AyZmV0YVV6TUJrCkVoRkIrLzh5Ymw3UGlRb2hxb3JR
            OWYrNXVnUTZuVjYwMnB1QTE4TDdhT2sKLS0tIDNUVmlxUHpxdVNGajVCVzhUSUEz
            WGpKR3ZqTXZUaHYvN1h0Rnh6d1BuY28KNIArru03hIsvEiGdGLiPxLlBcAoac7X3
            dcBvbGTOWmgV6sd2wp16LydECJmxUaQrwcvBeH09/6wFE4j58ppzxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzfgngev8hy7jws5yxm0x535fqn5rctd3p5fa2z4xw9435lpm3cq37n2tc
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T14:36:07Z"
    mac: ENC[AES256_GCM,data:+DcmxyaNnv0mOpSbJWUFTaqSq8GVLhWiIDA4sWrzkAnc/DtVRgEksO965fsMiasw0Z1thMaqpKSgmmrODB0PRC3eEEmvzpnsOGXyy/m5rxoRBJwuUmS6DHfZAxEnNMslg2GQl+DdldBjPxbqG7hjteudcguiBq6v2lszfCkTNe8=,iv:mHfJ9iMG+U6XHPuE6RYrQI/zabLRVPO9Ytty3S14o+g=,tag:qTDUZchDj+zJZJSCjH+oLA==,type:str]
    version: 3.13.3
