# yamllint disable-file
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.storage.annotations | nindent 4 }}
spec:
  accessModes:
{{ toYaml .Values.storage.accessModes | nindent 4 }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
